### ISSUE TITLE
Cannot use import statement outside a module (While processing ~/node_modules/nativewind/babel.js)

### ISSUE THREAD

**Issue by dakshlohar1** [nativewind/nativewind#573] opened 2023-10-05 10:01 UTC
**Bug**

`OS`: linux/Ubuntu-20.04
`nativewind`: 2.0.11
`tailwindcss`: 3.3.2
`react-native`: 0.71.4
`typescript`: 4.8.4

I am not able to use the `platformSelect` function inside the **tailwind.config.js** whenever I try to define some properties based on the platform the react native app crashes. I created the **tailwind.config.js** at the root of my project directory.
Here is my **tailwind**
```javascript
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        wine: '#8C1D40',
        'wine-dark': require('nativewind').platformSelect({
          android: '#8C1D40',
          ios: '#8C1D10',
          default: '#8C1dd0',
        }),
      },
    },
  },
  plugins: [require('@tailwindcss/container-queries')],
};
```
I have the **src** directory at the root which contains all my code. I also added the `nativewind` plugin in the **babel.config.js** below is my babel config file code:
```javascript
/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        extensions: ['.js', '.json'],
        alias: {
          '@': './src',
          types: './@types',
        },
      },
    ],
    'nativewind/babel',
  ],
};

```

**To Reproduce**
1. Simply use any native-specific function in the tailwind.config.js theme and save the file.
2. Use any of the values or properties you defined in the tailwind theme and save.
3. Reload or restart the React native app

**Expected behavior**
I am should able to use the defined properties in the tailwind theme using `platformColor` function in my components.

**Screenshots**
This is the screenshot of the emulator:
![image](https://github.com/marklawlor/nativewind/assets/97943478/137b3aa0-e9da-432b-be61-e42a93f11d8f)
And this is the output of the console after the error:
![image](https://github.com/marklawlor/nativewind/assets/97943478/77e8ab21-f79c-427d-af50-989cd6d4f9ee)

**Comment by dakshlohar1** [comment] 2023-10-05 10:03
```tsx
import React from 'react';
import { ScrollView, Text, View } from 'react-native';

const App = () => {
  const [state] = React.useState(Array(1000).fill(100));
  return (
    <ScrollView className="gap-3">
      {state.map(() => (
        <View>
          <Text className="bg-wine-dark">Blah blah blah</Text>
        </View>
      ))}
    </ScrollView>
  );
};

export default App;
```
Here are the uses of defined value.

**Comment by partiellkorrekt** [comment] 2023-10-26 07:46
I just encountered the same bug. Here is a workaround, that I found:

```js
const {
  platformSelect,
  platformColor,
  hairlineWidth,
  pixelRatio,
  fontScale,
  getPixelSizeForLayoutSize,
  roundToNearestPixel
} = require('nativewind/dist/theme-functions')
```

You can pick whatever imports you need from this code. This doesn't fix the bug but it helps get the app running anyways :)

**Comment by MJdiop** [comment] 2023-11-19 00:00
i also have the same error  my configuration 
```
tailwind.config.js

import { themeColors } from './constants/Colors.ts';
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        ...themeColors,
      },
    },
  },
  plugins: [],
};

```

```
babel.config.js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['nativewind/babel', require.resolve('expo-router/babel')],
  };
};

```

![simulator_screenshot_A5530266-6BA2-477A-9B22-24BABE5E2506](https://github.com/marklawlor/nativewind/assets/98955234/acdee014-7f0f-4201-aebd-b1641e6d7a10)

**Comment by FranciscoMateusVG** [comment] 2023-11-24 12:15
I'm having the same issue. I followed the same configuration as @dakshlohar1 and got the same screen. Not even the proposed workaround from @partiellkorrekt is working.

**Comment by Abror4544** [comment] 2023-12-01 14:41
Any updates?

**Comment by vinibgoulart** [comment] 2023-12-02 01:07
same issue here

tailwind.config.ts
```
import { colors } from '@tiger-wallet/theme';

export default {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        pastel: {
          light: colors.pastel,
          main: colors.pastel,
          dark: colors.pastel,
        },
        primary: {
          light: colors.primary,
          main: colors.primary,
          dark: colors.primary,
        },
        secondary: {
          light: colors.secondary,
          main: colors.secondary,
          dark: colors.secondary,
        },
      },
    },
  },
  plugins: [],
};
```

```
Cannot use import statement outside a module (While processing: "/Users/viniciusblazius/Documents/projects/tiger-wallet/node_modules/nativewind/babel.js")
```

**Comment by MJdiop** [comment] 2023-12-02 01:35
@vinibgoulart you can try to change your import with require()

**Comment by vinibgoulart** [comment] 2023-12-02 02:09
i want to use typescript in my project

**Comment by bpoulaindev** [comment] 2023-12-15 15:52
I'm facing the same issue in a blank new project, still no workarounds ?

**Comment by MJdiop** [comment] 2023-12-15 20:28
they don't accept imports outside  modules using require or set values directly

**Comment by MJdiop** [comment] 2023-12-15 20:28
it worked for me

**Comment by bpoulaindev** [comment] 2023-12-15 20:35
> it worked for me

What did you change and where ? The only "import" I have is in the generated babel.js from nativewind, can't make a blank expo nativewind typescript project work

**Comment by MJdiop** [comment] 2023-12-15 21:35
I've changed the imports to set the value directly to

**Comment by MJdiop** [comment] 2023-12-15 21:41
I've just created an expo typescript project with nativewind and everything works. 

![app-ts](https://github.com/marklawlor/nativewind/assets/98955234/db1fb0be-0f84-4bd7-9f56-4e2d489a03e5)

![babel-config](https://github.com/marklawlor/nativewind/assets/98955234/847b7b80-9c45-4127-becc-daf6dfe15289)

![package-json](https://github.com/marklawlor/nativewind/assets/98955234/cadf2b8f-3e5a-4586-a343-6c7afcb5afaf)

![tailwind-config](https://github.com/marklawlor/nativewind/assets/98955234/6a0a0738-e174-4d69-a56d-26af41375d78)

![simulator_screenshot_7807FF6E-3A55-4C98-950B-EFFB52B0C7E4](https://github.com/marklawlor/nativewind/assets/98955234/0dd3e141-0304-443e-8c5f-f3d9767cb6c9)

**Comment by JoshMerlino** [comment] 2024-01-02 20:09
I think the issue is more about how babel is resolving imports in the `tailwind.config` file.

In my project, I want to import colors from my monorepo,

### tailwind.config.js *(dosnt work)*
```js
const { colors } = require("@embervpn/assets");

/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./**/*.{js,jsx,ts,tsx}"
	],
	theme: {
		extend: {
			colors
		},
	},
	plugins: [],
};
```
The above snippet dosnt work, even though babel and typescript are configured properly, as well as the package being a commonjs module. Should be no issues importing but we get the following error:
```
error: index.ts: [BABEL] /PROJECT/apps/native/index.ts: Unexpected token 'export' (While processing: "/PROJECT/node_modules/nativewind/babel.js")
```

However as soon as I go to a project file, such as my main `App.tsx`, and import, there are no issues...

### App.tsx *(works correctly)*
```tsx
import { colors } from "@embervpn/assets";
import { ActivityIndicator } from "react-native-paper";

export default function Page() {

	// Loading
	return <ActivityIndicator
		animating={ true }
		color={ colors.primary[500] }
		size="large" />;
	
}
```

Is there anything glaringly obvious I'm doing wrong that I'm just not seeing?

**Comment by iRoySwift** [comment] 2024-01-17 06:47
```ts
// tailwind.config.ts
const colors = require("tailwindcss/colors");

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        colors: {
            ...colors,
            primary: colors.cyan[900],
            darkText: colors.zinc[700],
            lightText: colors.white,
        },
        extend: {},
    },
    plugins: [],
};
```
I modified the configuration to :

```ts
// tailwind.config.ts
import type { Config } from "tailwindcss";
import colors from "tailwindcss/colors";

/** @type {import('tailwindcss').Config} */
export default {
    content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        colors: {
            ...colors,
            primary: colors.cyan[900],
            darkText: colors.zinc[700],
            lightText: colors.white,
        },
        extend: {},
    },
    plugins: [],
};

```

This way I can use typescript hints

```ts
import resolveConfig from "tailwindcss/resolveConfig";
import { useMemo } from "react";
import type { Config } from "tailwindcss";
import tailwindConfig from "tailwind.config";

const useTailwind = () => {
    const tailwind = useMemo(() => resolveConfig(tailwindConfig), []);
    return tailwind;
};

export default useTailwind;

```

**Comment by FritzAxel** [comment] 2024-03-05 18:44
Hey, do you find any solution? 

I am not using TS and have the same issue.

At the[ nativewind's docs](https://www.nativewind.dev/customization/theme
) says that we have to import it but it doesn't work.


<img width="830" alt="image" src="https://github.com/marklawlor/nativewind/assets/15350252/8fe36973-7cc0-455d-bdb4-bc1542e15c5e">

**Comment by rbc33** [comment] 2024-03-11 21:02
althought its not the best, you can define a classname or part of it like a specific font for each platform in a ts, or js file and export it, it's no ideal but works and i add it later to the classname to get the font, same for the margin top

`import { platformSelect } from "nativewind";

const fontClassName = platformSelect({
  ios: " font-[Avenir] ",
  android: " font-[Roboto] ",
  web: " text-sans ",
});
export default fontClassName;
`

**Comment by VarshithPawarHR** [comment] 2024-07-17 11:48
Has anyone found the solution ??

**Comment by VarshithPawarHR** [comment] 2024-07-18 09:57
hi there it just got resolved i deleted all the tailwind files and executed it again dont know how

**Comment by ikolokoltsev** [comment] 2024-07-24 15:06
Solution 1:
If you are using `tailwind.config.ts` replace it with 'tailwind.config.js', worked for me.
Solution 2:
Remove bable from your project, I'm not sure why you need it in the RN project.

**Closed** 2024-09-02 23:10 UTC
Labels: issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:25
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
