### ISSUE TITLE
Passing different color of text is not being applied if already set in component 

### ISSUE THREAD

**Issue by MariuzM** [nativewind/nativewind#1363] opened 2024-12-21 03:26 UTC
**Describe the bug**
When passing "text-primary-400" its not being applied but still uses "text-primary-600" 

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/fa591a25-c47d-4dd0-8492-b3cf43c02824" />

**Reproduction**
Please see our contribution guide: https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue

Please provide a reproduction of the issue using one of the following templates:
- **StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
- **Create Expo Stack template**: 
  - `npx create-expo-stack@latest --nativewind`
  - `npx create-expo-stack@latest --nativewind --expo-router`

**Expected behavior**

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by marklawlor** [comment] 2024-12-21 10:51
Please provide a full reproduction repro. Issues like this are normally caused by a misconfigured `tailwind.config.js#content` glob, but you did not provide that information so we cannot verify or troubleshoot your issue

**Comment by danstepanov** [comment] 2024-12-23 20:08
no repro, closing

**Closed by danstepanov** 2024-12-23 20:08 UTC

**Comment by MariuzM** [comment] 2024-12-24 03:11
Sorry forgot, i cant post repo because its prod app.
What else i could provide that helps? using `twMerge` solved this issue 

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        black: {
          100: '#E6E7E7',
          200: '#CECED0',
          300: '#9C9EA1',
          400: '#6B6D71',
          500: '#393D42',
          600: '#080C13',
          700: '#060A0F',
          800: '#05070B',
          900: '#030508',
          1000: '#020204',
        },
        primary: {
          100: '#FFFFFF',
          200: '#F6F7F9',
          300: '#AFE67F',
          400: '#7F17ED',
          500: '#1D3208',
          600: '#080C13',
          700: '#2556C8',
          800: '#EB4969',
          900: '#FFD23F',
          1000: '#2F384C',
        },
      },
    },
  },
  plugins: [],
};
```
