### ISSUE TITLE
Frameless instructions don't work

### ISSUE THREAD

**Issue by ollyde** [nativewind/nativewind#1176] opened 2024-11-01 13:49 UTC
Following the instructions here https://www.nativewind.dev/getting-started/react-native

```
error: SyntaxError: /lib/global.css: Leading decorators must be attached to a class declaration. (1:10)

> 1 | @tailwind base;
    |           ^
  2 | @tailwind components;
  3 | @tailwind utilities;
 BUNDLE  ./index.js 

 LOG  Running "react_native" with {"rootTag":11,"initialProps":{"concurrentRoot":false}}
```

babel.config.js
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['module:@react-native/babel-preset', 'nativewind/babel'],
    plugins: [['@babel/plugin-proposal-decorators', {legacy: true}]],
  };
};
```
metro.config.js
```
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const {withNativeWind} = require('nativewind/metro');

const config = mergeConfig(getDefaultConfig(__dirname), {
  /* your config */
});

module.exports = withNativeWind(config, {input: './global.css'});

```

**Comment by coycoylaniba** [comment] 2024-11-03 21:51
i'm also having similar issue:
```
 ERROR  SyntaxError in global.css: unrecognized character '@' (1:0)
@tailwind base;
```

**Comment by ollyde** [comment] 2024-11-03 21:57
Nativewind is bad, just use twrnc @coycoylaniba 

```
// tw.config.ts
import { create } from 'twrnc';

import tailwindConfig from '@/tailwind.config';

const tw = create({
  theme: (tailwindConfig.theme as any),
});

export default tw;
```

Use like this
```
 <View>
      <Text style={tw`mt-24 text-black text-lg underline`}>
        {'Test on mobile'}
      </Text>
    </View>
```

**Comment by coycoylaniba** [comment] 2024-11-03 22:15
@ollyde i will try this out!

**Comment by marklawlor** [comment] 2024-11-03 22:38
Please provide a full reproduction, I cannot assist you when you only choose to share 2 files. This similar to saying your car makes a sound and sending them a picture of the door 🤷‍♂️ This issue template requests all the information needed. Choosing to ignore the template means your omitting vital information I need.

> Nativewind is bad, just use twrnc

I also do not appreciate comments like this. People can do their own research on the two libraries. `twrnc` is great if you only need basic static styling. NativeWind was designed for complex dynamic styling.

I'm closing this issue because of lack of information and I do no appreciate the attitude. Please create a new issue that follows the issue template if you require support.

**Closed by marklawlor** 2024-11-03 22:38 UTC

**Comment by marklawlor** [comment] 2024-11-04 10:18
@ollyde This is a volunteer open source project, if you found the instructions confusing we'd really appreciate a PR to clarifies the confusing sections.

> There's no samples using the latest of the framework

The only officially supported framework for [React Native is Expo](https://reactnative.dev/docs/environment-setup). There is an [Expo example in this repo](https://github.com/nativewind/nativewind/tree/main/examples/expo-router). Also there are multiple "template" project generators like `npm create expo-stack --expo-router --nativewind`.  https://rn.new/

What other examples would like you and/or what framework are you referring to? 

We also have a discord where user's can get real time support from the team of volunteers

> Why does RN have import.css when it doesn't even support CSS.

The primary purpose of NativeWind is to add support of `.css` imports. I'm not sure how to answer this feedback?

**Comment by ollyde** [comment] 2024-11-04 10:20
@marklawlor if this was the case, then why not mark that on the readme instead of writing it here and letting people waste hours of their time.

**Comment by marklawlor** [comment] 2024-11-04 10:29
Which point are you referring to?

Frameworkless does work, and many people use it. We just don't have an example in this repro. 

Also, our entire test suite is run in a framework-less project. Just because we're trying to minimise on dependancies 👍

**Comment by brandtnewlabs** [comment] 2024-12-02 21:44
The frameless instruction DOES work! I had errors too, but it was because I missed a few lines of configuration in the metro.config. Running great on 0.75.4 🚀  Thanks a lot @marklawlor
