### ISSUE TITLE
[4.1] Nativewind received no data.

### ISSUE THREAD

**Issue by kelokchan** [nativewind/nativewind#1050] opened 2024-09-07 13:03 UTC
**Describe the bug**

Getting the following error while upgrading Nativewind to 4.1. The app was working fine when using v4.0.36

![Simulator Screenshot - iPhone 15 - 2024-09-07 at 20 53 48](https://github.com/user-attachments/assets/6212bf3d-2896-4584-9937-0cd1885da748)

**Reproduction**
Please see our contribution guide: https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue

Please provide a reproduction of the issue using one of the following templates:
- **StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
- **Create Expo Stack template**: 
  - `npx create-expo-stack@latest --nativewind`
  - `npx create-expo-stack@latest --nativewind --expo-router`

**Expected behavior**

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

`babel.config.js`
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
    plugins: ["react-native-reanimated/plugin"],
  };
};
```

`tailwind.config.js`
```
const { hairlineWidth } = require("nativewind/theme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        rating: {
          DEFAULT: "hsl(var(--rating))",
          foreground: "hsl(var(--rating-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderWidth: {
        hairline: hairlineWidth(),
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      fontFamily: {
        dmSans: ["DMSans_400Regular"],
        dmSansMedium: ["DMSans_500Medium"],
        dmSansBold: ["DMSans_700Bold"],
      },
      fontSize: {
        xs: ["12px", "16px"],
        sm: ["14px", "20px"],
        base: ["16px", "24px"],
        lg: ["18px", "28px"],
        xl: ["20px", "28px"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
```

`global.css`
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;
    --card: 0 0% 100%;
    --card-foreground: 240 10% 3.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 240 10% 3.9%;
    --primary: 75.3, 96.3%, 68%;
    --primary-foreground: 0 0% 98%;
    --secondary: 240 4.8% 95.9%;
    --secondary-foreground: 240 5.9% 10%;
    --muted: 240 4.8% 95.9%;
    --muted-foreground: 240 3.8% 46.1%;
    --accent: 43.2 100% 59.4%;
    --accent-foreground: 240 5.9% 10%;
    --rating: 256 86% 48%;
    --rating-foreground: 210 40% 98%;
    --success: 122.7 39.1% 49.8%;
    --success-foreground: 210 40% 98%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 0 0% 98%;
    --warning: 29 88% 56%;
    --warning-foreground: 210 40% 98%;
    --border: 240 5.9% 90%;
    --input: 240 5.9% 90%;
    --ring: 240 5.9% 10%;
  }

  .dark:root {
    --background: 240 10% 3.9%;
    --foreground: 0 0% 98%;
    --card: 240 10% 3.9%;
    --card-foreground: 0 0% 98%;
    --popover: 240 10% 3.9%;
    --popover-foreground: 0 0% 98%;
    --primary: 75.3, 96.3%, 68%;
    --primary-foreground: 240 5.9% 10%;
    --secondary: 0 0% 100%;
    --secondary-foreground: 240 10% 3.9%;
    --muted: 240 3.7% 15.9%;
    --muted-foreground: 240 5% 64.9%;
    --accent: 240 3.7% 15.9%;
    --accent-foreground: 0 0% 98%;
    --rating: 256 86% 48%;
    --rating-foreground: 210 40% 98%;
    --success: 122.7 39.1% 49.8%;
    --success-foreground: 210 40% 98%;
    --destructive: 0 72% 51%;
    --destructive-foreground: 0 0% 98%;
    --warning: 43.2 100% 59.4%;
    --warning-foreground: 210 40% 98%;
    --border: 0 0% 27%;
    --input: 240 3.7% 15.9%;
    --ring: 240 4.9% 83.9%;
  }
}
```

`metro.config.js`
```
const { getDefaultConfig } = require("expo/metro-config");
const fs = require("fs");
const { FileStore } = require("metro-cache");
const { withNativeWind } = require("nativewind/metro");
const path = require("path");

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, "../..");

const config = getDefaultConfig(projectRoot);

// #1 - Watch all files in the monorepo
config.watchFolders = [
  ...config.watchFolders,
  workspaceRoot,
];

// #2 - Try resolving with project modules first, then workspace modules
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
];


// Use turborepo to restore the cache when possible
config.cacheStores = [
  new FileStore({
    root: path.join(projectRoot, "node_modules", ".cache", "metro"),
  }),
];

// Apply NativeWind configuration
const modifiedConfig = withNativeWind(config, { input: "./global.css" });

// Ensure the resolver changes are not overwritten by withNativeWind
modifiedConfig.resolver = {
  ...modifiedConfig.resolver,
  resolveRequest: config.resolver.resolveRequest,
};

module.exports = modifiedConfig;
```

Expo Env Info
```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 4.3.1 - ~/.yarn/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/kelokchan/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 16.0/16A5202i - /usr/bin/xcodebuild
    Expo Workflow: bare
```

Dependencies:
```
expo": "52.0.0-canary-20240904-69100c1",
    "expo-application": "6.0.0-canary-20240904-69100c1",
    "expo-asset": "11.0.0-canary-20240904-69100c1",
    "expo-av": "15.0.0-canary-20240904-69100c1",
    "expo-blur": "14.0.0-canary-20240904-69100c1",
    "expo-clipboard": "7.0.0-canary-20240904-69100c1",
    "expo-constants": "17.0.0-canary-20240904-69100c1",
    "expo-crypto": "14.0.0-canary-20240904-69100c1",
    "expo-dev-client": "5.0.0-canary-20240904-69100c1",
    "expo-device": "7.0.0-canary-20240904-69100c1",
    "expo-font": "13.0.0-canary-20240904-69100c1",
    "expo-image": "2.0.0-canary-20240904-69100c1",
    "expo-image-picker": "16.0.0-canary-20240904-69100c1",
    "expo-linking": "7.0.0-canary-20240904-69100c1",
    "expo-navigation-bar": "3.0.8-canary-20240904-69100c1",
    "expo-notifications": "1.0.0-canary-20240904-69100c1",
    "expo-router": "4.0.0-canary-20240904-69100c1",
    "expo-secure-store": "14.0.0-canary-20240904-69100c1",
    "expo-splash-screen": "1.0.0-canary-20240904-69100c1",
    "expo-status-bar": "1.12.2-canary-20240904-69100c1",
    "expo-system-ui": "4.0.0-canary-20240904-69100c1",
    "expo-web-browser": "14.0.0-canary-20240904-69100c1",
    "nativewind": "4.1.6",
    "react": "18.2.0",
    "react-countdown": "^2.3.6",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.52.2",
    "react-icomoon": "^2.5.7",
    "react-native": "0.75.2",
    "tailwind-merge": "^2.5.2",
    "tailwindcss": "3.4.4",
    "tailwindcss-animate": "^1.0.7"
```

**Comment by danstepanov** [comment] 2024-09-09 20:07
Please provide a reproduction of the issue using one of the following templates:

StackBlitz template: https://stackblitz.com/edit/nativewind-test?view=editor
Create Expo Stack template:
npx create-expo-stack@latest --nativewind
npx create-expo-stack@latest --nativewind --expo-router

**Comment by danstepanov** [comment] 2024-09-09 20:08
Closing until there's a repro

**Closed** 2024-09-09 20:09 UTC
Labels: needs reproduction, v4.1

**Comment by marklawlor** [comment] 2024-09-10 01:33
You are overriding the NativeWInd `resolveRequest` in your `metro.config.js`

**Comment by octalpixel** [comment] 2024-09-10 21:02
> hey @marklawlor and @danstepanov, getting the same error for a project that I migrated from v2 to v4. I sent request to the repo , if you guys want to have a look at it. The repo name is "v2-to-v4-repo" (just incase you want to find it in your email)

All good. After 2 days I just figured out I was resolving  an old metro version.

**Comment by zegenerative** [comment] 2024-09-26 10:58
@octalpixel what did you do exactly? I'm having the same issue

**Comment by octalpixel** [comment] 2024-09-26 16:11
> @octalpixel what did you do exactly? I'm having the same issue

I was migrating an old project from expo 49 to 52 , and then nativewind 2 to 4. The code has resolution in the package.json (yarn) for an old metro version. Removing that helped, and did another  yarn install again. 

So I don't know the right answer, doing the above helped me, but check if your metro is update to date.

**Comment by zegenerative** [comment] 2024-09-27 07:35
Didn't help. 
Expo 51
NW 4.0.1

**Comment by zegenerative** [comment] 2024-09-27 09:08
For anyone stumbling upon this: make sure 
`import ./global.css` is present in your app code. 
:)

**Comment by octalpixel** [comment] 2024-09-27 11:40
> For anyone stumbling upon this: make sure `import ./global.css` is present in your app code. :)

Oh lol xD. That was actually confusing because that instruction is at the end of the docs of that page.

**Comment by zegenerative** [comment] 2024-09-27 11:56
In my case it disappeared because of a merge conflict

**Comment by octalpixel** [comment] 2024-09-27 15:48
> In my case it disappeared because of a merge conflict

Glad it worked out! How is your Nativewind experience ? Have you used it before ?

**Comment by sarabEriced** [comment] 2025-07-09 12:48
I have an updated Metro version instead (@0.20.17)... here my files... anyone can help me?
My app is a React Native app for smartphone that I created yesterday with `npx create-expo-app@latest`.
I've already deleted node_modules/ and reruned `npm install` and used `npx expo install --fix`.
I started the project `expo start -c`, but the app still not working....

package.json
```
{
  "name": "fpnet-mobile",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "lint": "expo lint"
  },
  "dependencies": {
    "@expo/metro-runtime": "~5.0.4",
    "@expo/vector-icons": "^14.1.0",
    "@react-navigation/bottom-tabs": "^7.3.10",
    "@react-navigation/elements": "^2.3.8",
    "@react-navigation/native": "^7.1.6",
    "expo": "~53.0.17",
    "expo-blur": "~14.1.5",
    "expo-constants": "~17.1.7",
    "expo-font": "~13.3.2",
    "expo-haptics": "~14.1.4",
    "expo-image": "~2.3.2",
    "expo-linking": "~7.1.7",
    "expo-router": "~5.1.3",
    "expo-splash-screen": "~0.30.10",
    "expo-status-bar": "~2.2.3",
    "expo-symbols": "~0.4.5",
    "expo-system-ui": "~5.0.10",
    "expo-web-browser": "~14.2.0",
    "nativewind": "^4.1.23",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-native": "0.79.5",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-web": "~0.20.0",
    "react-native-webview": "13.13.5"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/react": "~19.0.10",
    "eslint": "^9.25.0",
    "eslint-config-expo": "~9.2.0",
    "prettier-plugin-tailwindcss": "^0.6.13",
    "tailwindcss": "^3.4.17",
    "typescript": "~5.8.3"
  },
  "private": true
}
```


metro.config.js
```
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './global.css' });
```

babel.config.js
```
module.exports = function (api) {
  api.cache(true);
  let plugins = [];

  return {
    presets: [['babel-preset-expo', { jsxImportSource: 'nativewind' }], 'nativewind/babel'],

    plugins,
  };
};
```

tailwind.config.js
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,ts,tsx}', './components/**/*.{js,ts,tsx}'],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

app-env.d.ts
```
// @ts-ignore
/// <reference types="nativewind/types" />
```

global.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

nativewind-env.d.ts
```
/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
```

expo-env.d.ts
```
/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git ignore
```
