### ISSUE TITLE
Colorscheme is reset/changed when AppState changes

### ISSUE THREAD

**Issue by nathan995** [nativewind/nativewind#1360] opened 2024-12-14 09:52 UTC
**Describe the bug**
When color scheme is set to `system` and the AppState changes, the color scheme resets or changes unexpectedly. 

**Reproduction**
A reproducible example can be found here: https://github.com/nathan995/nativewind-appstate

To reproduce the issue:
1. Open the app and set the color scheme to `system`.
2. Put the app into inactive state.
3. Bring the app back to the foreground.

**Expected behavior**
The color scheme should persist when the AppState changes

**Additional context**
Issue only happens when the device is set to `dark appearance` and color scheme changes from `dark` -> `system`. Going from `light` -> `system` doesn't trigger the reset.

https://github.com/user-attachments/assets/0e429cc4-7849-4bcb-a17f-a953d3342686

**Comment by devYonz** [comment] 2024-12-26 10:09
Same issue. This is a fundamental requirement, any updates on a solution or root cause? Nobody can use native wind on new arch without a fix for this.

**Comment by nathan995** [comment] 2024-12-27 13:03
Issue was actually caused by React Native. See https://github.com/facebook/react-native/issues/47725#issuecomment-2486523116 for a patch

**Closed** 2024-12-27 13:04 UTC
