### ISSUE TITLE
"TypeScript Error with `className` Prop in React Native Using NativeWind"

### ISSUE THREAD

**Issue by amehmeto** [nativewind/nativewind#741] opened 2024-01-15 03:41 UTC
Describe the bug
TypeScript error in a React Native project using NativeWind for Tailwind CSS. The compiler throws an error related to the className prop, which is not recognized on React Native components.

To Reproduce

Set up a React Native project with NativeWind and TypeScript.
Follow the NativeWind documentation to configure TypeScript (tsconfig.json and app.d.ts).
Attempt to use the className prop in a React Native component.
TypeScript compiler throws the following error:
python
Copy code
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ViewProps | Readonly<ViewProps>): View', gave the following error.
    Type '{ children: Element[]; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'
  Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'
  Overload 2 of 2, '(props: ViewProps, context: any): View', gave the following error.
    Type '{ children: Element[]; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'
  Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'
Expected behavior
The className prop should be recognized by TypeScript and allow the usage of Tailwind CSS classes in React Native components.

Expo Snack
Not applicable / No Expo Snack available.

Screenshots
N/A

Additional context

React Native Version: 0.72.6
NativeWind Version: 2.0.11
TypeScript Version: 5.3.3
Expo SDK Version: 49.0.15
I followed the NativeWind documentation for TypeScript setup, yet the issue persists. I have tried reinstalling node modules, clearing cache, and restarting the TypeScript server, with no success. This issue appears to be specific to TypeScript's recognition of the className prop introduced by NativeWind in a React Native project.

https://stackoverflow.com/questions/77817553/typescript-error-with-nativewind-in-react-native-no-overload-matches-this-call

**Comment by Brentably** [comment] 2024-02-02 01:49
Having the same issue.

**Comment by fergalmoran** [comment] 2024-02-06 17:42
This is a duplicate of https://github.com/marklawlor/nativewind/issues/77

Ignore the first suggestion, the actual solution is here, worked for me!!
https://www.nativewind.dev/getting-started/typescript

**Comment by osvald0** [comment] 2024-06-12 05:13
The issue persists from my side, and the suggested fix doesn't work. Any more information about this?

**Comment by seifmostafa73** [comment] 2024-06-29 20:41
> The issue persists from my side, and the suggested fix doesn't work. Any more information about this?

Same here

**Comment by MaizNadeem** [comment] 2024-08-08 15:53
> > The issue persists from my side, and the suggested fix doesn't work. Any more information about this?
> 
> 1. Ensure that you have named it `nativewind-env.d.ts` not `app.d.ts`
> 2. Ensure it's in the same directory as the app.json (you main directory)
> 3. Restart you VsCode

I think for @osvald0, another possibility might be with `tsconfig.json` itself. 

For example:

```
{
	"extends": "expo/tsconfig.base",
	"compilerOptions": {
		"target": "esnext",
		"module": "esnext",
		"strict": true,
		"esModuleInterop": true,
		"skipLibCheck": true,
		"forceConsistentCasingInFileNames": true,
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"jsx": "react-jsx",
		"allowSyntheticDefaultImports": true,
		"noImplicitAny": true,
		"strictNullChecks": true,
		"strictFunctionTypes": true,
		"strictBindCallApply": true,
		"strictPropertyInitialization": true,
		"noImplicitThis": true,
		"alwaysStrict": true
	},
	"include": ["src/**/*", "env.d.ts"]
}
```

If I have "inlude" array set up in my tsconfig, I have to make sure that nativewind's directive file eg. `my-app.d.ts` stays in the same directory. In this case, `src`. If you do not have the "include" attribute, it should just be inside root directory.

**Comment by gunnartorfis** [comment] 2024-08-16 11:50
After upgrading to RN 0.74.2+, from 0.74.1, this breaks for me. As soon as I downgrade back to 0.74.1, the errors goes away. I'm using Expo, was on ~51.0.8, now bumping to ~51.0.28. 

Any idea what might be causing that?

**Comment by gunnartorfis** [comment] 2024-08-16 14:20
Update: Upgrading to RN 0.75.1 fixes this.

**Comment by Sunrisies** [comment] 2024-08-30 15:10
> The issue persists from my side, 和 the suggested fix doesn't work. Any more information about this?我这边问题仍然存在，并且建议的修复不起作用。有关于此的更多信息吗？

如果使用pnpm 进行安装的话，就引起这个问题

**Closed** 2024-09-02 23:10 UTC
Labels: issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:20
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
