### ISSUE TITLE
[V4] error building in expo

### ISSUE THREAD

**Issue by jrwpatterson** [nativewind/nativewind#995] opened 2024-08-13 12:23 UTC
**Describe the bug**
I'm getting a weird error on expo. 

I'm getting the folowing error
```
 Executing dossy » Bundle React Native code and images
    Bundler cache is empty, rebuilding (this may take a minute)

❌  error: global.css: A jest worker process (pid=4068) was terminated by another process: signal=SIGTERM, exitCode=null. Operating system logs may contain more information on why this occurred.
```

if I try to build the code locally with Xcode I get this... 
```
tailwindcss(ios) rebuilding... tailwindcss(ios) is taking a long time to build, please read https://tailwindcss.com/docs/content-configuration#pattern-recommendations to speed up your build time
```

It works locally when running and its a pretty fresh app. I tworks for android builds it just the IOs ones

"expo": "~51.0.26",
"nativewind": "4.0.36",
"tailwindcss": "3.4.2",
"react-native": "0.74.5",
"react-native-reanimated": "3.10.1",

**Comment by 007jedgar** [comment] 2024-08-16 13:14
Also getting the same error with eas build. Adding more context:
```
Executing appname » Bundle React Native code and images
    Bundler cache is empty, rebuilding (this may take a minute)

❌  (global.css:-1)

  1 | @tailwind base;
  2 | @tailwind components;
  3 | @tailwind utilities;
▸ ** ARCHIVE FAILED **
```
xcode logs
```
> 1 | @tailwind base;

    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  2 | @tailwind components;

  3 | @tailwind utilities;

  4 |

    at ModuleResolver.resolveDependency (/Users/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
...
```

**Comment by 007jedgar** [comment] 2024-08-16 13:57
I got it to work after a few steps

I migrated to your versions:
```
"tailwindcss": "3.4.2",
"nativewind": "4.0.36",
```

deleted nodemodules and watchman
```
rm -rf node_modules .cache
watchman watch-del-all
```

updated the production key
```
"build": {
    "production": {
      "cache": {
        "key": "0.0.1" <---changed this
      },
}

```

ran prebuild **clean**  and built it with success
```
npm install
npx expo prebuild --clean
eas build:configure 
eas build --platform ios 
```

**Comment by robinsadeghpour** [comment] 2024-09-01 13:40
I have the same issue

**Comment by danstepanov** [comment] 2024-09-02 23:42
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by thonyromes** [comment] 2024-09-05 20:27
> I have the same issue

Have you been able to fix this?

**Comment by StonedTD** [comment] 2024-10-04 20:04
I faced the same issue and struggled for a while, trying in vain to resolve it. Reinstalling node_modules, clearing the cache and similar actions didn't help. What did work was adding this:
```
  "env": {
    "NODE_OPTIONS": "--max-old-space-size=4096"
  }
```
to the corresponding `build` section in eas.json (`production` in my case).

This effectively increases the memory allocation for V8's old memory space to a maximum of 4MiB.

I hope this helps someone.

Wishing everyone good luck and persistence in their development journey! :)

**Comment by elyobo** [comment] 2024-10-09 21:00
I can build locally with no problems using `--local` but I get the OP's error when using cloud build.

I'm confused as to what `jest` is doing in there at all, new to eas build but it seems like tests shouldn't be run at all (looks like it takes deliberate extra steps to get these to run).

**Comment by danstepanov** [comment] 2024-10-09 21:35
@elyobo which version of NativeWind are you running?

**Comment by elyobo** [comment] 2024-10-09 21:36
```
npm ls nativewind
uplist@1.0.0 /Users/loboyle/src/uplist
├─┬ @gluestack-ui/nativewind-utils@1.0.23
│ └── nativewind@4.0.36 deduped
├─┬ @legendapp/motion@2.4.0
│ └── nativewind@4.0.36 deduped
└── nativewind@4.0.36 overridden
```

**Comment by elyobo** [comment] 2024-10-10 01:19
Update: I still have no idea why `jest` is involved at all but allowing more memory as suggested above does get things working for me 🤷

**Comment by flippingtables** [comment] 2024-10-13 20:07
I hit this same issue in M1 Sonoma 14.7. The expo build was stuck at the "Bundle React Native code and images" step when using Nativewind 4.1.16. When i downgraded to 4.1.10 build works fine again.

**Comment by Yidne21** [comment] 2024-10-14 14:25
I got the same issue here 

error: global.css: A jest worker process (pid=31501) was terminated by another process: signal=SIGTERM, exitCode=null. Operating system logs may contain more information on why this occurred

**Comment by danstepanov** [comment] 2024-10-15 18:07
> @danstepanov I'm using the current `canary` version. I note your comment about 4.1 being released; should we be upgrading? The guidance in the README put me off.
> 
> <img alt="image" width="681" src="https://private-user-images.githubusercontent.com/407806/375140283-ff9c9cbc-5d47-4c14-bebf-6c691fdb040a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTU3OTIsIm5iZiI6MTcyOTAxNTQ5MiwicGF0aCI6Ii80MDc4MDYvMzc1MTQwMjgzLWZmOWM5Y2JjLTVkNDctNGMxNC1iZWJmLTZjNjkxZmRiMDQwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxODA0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjU3MTkxYmQzNmZkMDYzN2NmZGU2NTEyZGI4OTYyNTVkOTJlYjIyMjJjMTkwZmFjZjdhYmE3MGY1ZGI2ZjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e7AT6otB4M64VFk68yicbOD735AowEZPdzuWI23FcHE">
> ```
> npm ls nativewind
> myproject@1.0.0 /Users/loboyle/src/myproject
> ├─┬ @gluestack-ui/nativewind-utils@1.0.23
> │ └── nativewind@4.0.36 deduped
> ├─┬ @legendapp/motion@2.4.0
> │ └── nativewind@4.0.36 deduped
> └── nativewind@4.0.36 overridden
> ```
> 
> As noted, I really don't get what `jest` is doing running in there at all, is that expected somehow?

if you're confused as to why jest is included in nativewind, most of nativewind's development occurs in a jest test environment. We make changes and run the myriad of tests to ensure nothing has broken.

**Comment by danstepanov** [comment] 2024-10-15 18:07
I'll chat with mark about this tomorrow during our live stream

**Comment by elyobo** [comment] 2024-10-16 23:14
> if you're confused as to why jest is included in nativewind, most of nativewind's development occurs in a jest test environment. We make changes and run the myriad of tests to ensure nothing has broken.

That's what I'd expect if I was developing nativewind, not if I'm building a project that uses it (I don't expect the test suites of my dependencies to run during the build step for my own project, that would take forever and be testing things out of my control anyway), so I'm still pretty confused.

> In order to chat with mark about this, I'll need a repro tho

Seems to just be a memory limit thing, as the suggested "increase node memory" fix works for me. If jest running is expected then presumably no bug.

**Comment by marklawlor** [comment] 2024-10-21 23:27
Fixed in `4.1.18`.

Form my testing, this issue is very project dependant. If you are still experiencing this issue please create a new issue with a reproduction. This is not something we can resolve without a reproduction.

**Closed by marklawlor** 2024-10-21 23:27 UTC
Labels: needs reproduction, issue-wipe-pre-v4, v4.1

**Comment by Seanmclem** [comment] 2024-11-25 00:44
This error goes away after I update natvewind from `4.0.x` to `4.1.x` with `npm install nativewind@latest`

**Comment by OcttaDev** [comment] 2024-12-26 13:27
This error has become quite recurrent in some of my projects, including some incompatibilities with other libs that depend on nativewind. I migrated to version 4.1.23 and it worked normally!!

npm install nativewind@latest
