### ISSUE TITLE
newArchEnabled - Expo 51/52 not working

### ISSUE THREAD

**Issue by alisanoelia** [nativewind/nativewind#1328] opened 2024-11-15 15:52 UTC
I have tried creating a new project with Expo 52 and its new architecture, but when building the project, several errors occur. Although it works in Expo Go and during development, it doesn’t work when building the APK.

I’m not sure what the problem is, but it would be good to review it. I’ve tested it with Expo 51.0.39, and there are no issues.

Adding `"newArchEnabled": true` in the `app.json` file causes errors when building the package.

Info:

Expo SDK 51/52
Nativewind 4.1.23
Tailwindcss 3.4.15

**Comment by marklawlor** [comment] 2024-11-15 20:17
The new architecture changes are React Native communicates with the native layer

NativeWind operates within the JavaScript layer. While it looks magical, it's just another JavaScript component.

NativeWind has been tested on multiple apps running the new architecture.

This is why we have an issue template and why you should provide a reproduction repro. if you have an issue there is a high chance that the cause of your problem is something that you don't understand fully. Without a reproduction, I can't provide you any answers. I'm going to close this issue, if you'd like to receive support please create a new issue with a reproduction repro

**Closed** 2024-11-15 20:17 UTC

**Comment by alisanoelia** [comment] 2024-11-16 13:07
I understand

Thank you.
