### ISSUE TITLE
Doesn't get started

### ISSUE THREAD

**Issue by TomAndrewRocks** [nativewind/nativewind#909] opened 2024-05-07 17:34 UTC
node_modules\expo-router/entry.js ▓▓▓▓░░░░░░░░░░░░ 26.4% (134/267)

it stucked right here during the final setup of my expo router/nativewind configuration

**Comment by hello112334** [comment] 2024-05-08 03:55
same issue with
"nativewind": "4.0.36",
"tailwindcss": "^3.4.3"

**Comment by danharten-sovtech** [comment] 2024-05-09 14:37
@TomAndrewRocks I had luck with this today, can you drop a minimal reproducible example and I can _maybe_ see the issue?

**Comment by do-wa** [comment] 2024-05-28 19:15
I'm having the same issue on Win 11 when using the command:
`npx create-expo-app@latest -e with-router-tailwind`

But it does work when using devcontainers (linux)

**Comment by guibzo** [comment] 2024-06-28 16:12
Same issue here.
It works just fine on Android, but on Web the compiling just crashes and stops loading:
![image](https://github.com/nativewind/nativewind/assets/119091492/b0b468a6-897b-49f4-971f-4bb6fb166083)

Using:
- Windows 10;
- Expo v.51.0.16
- Expo Router v.3.5.17
- NativeWind v.4.0.1
- React/React DOM v.18.2.0
- React Native Web v.0.19.10

```js
// babel.config.js
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [['babel-preset-expo', { jsxImportSource: 'nativewind' }], 'nativewind/babel'],
  }
}
```

```js
// metro.config.js
const { getDefaultConfig } = require('expo/metro-config')
const { withNativeWind } = require('nativewind/metro')

const config = getDefaultConfig(__dirname)

module.exports = withNativeWind(config, { input: './src/styles/global.css' })
```

```js
// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ['./src/**/*.{ts,tsx}', './app/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

app.json has the "bundler": "metro" config inside of expo/web.

**Comment by hello112334** [comment] 2024-07-22 09:51
@younes200 

works. fixed with 
```
"nativewind": "^2.0.11",
"tailwindcss": "^3.3.2",
```

``` package.json
{
  "name": "itsalie",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "dev": "expo start -c --ios",
    "dev:web": "expo start -c --web",
    "dev:android": "expo start -c --android",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start -c --web",
    "format": "biome check --no-errors-on-unmatched --apply .",
    "postinstall": "npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.21",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.9",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.18",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "nativewind": "^2.0.11",
    "postcss-loader": "^4.2.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.3",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10",
    "tailwind-merge": "^2.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.2.45",
    "@types/react-native": "^0.73.0",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.3",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "^3.3.2",
    "typescript": "~5.3.3"
  },
  "private": true
}

```

**Comment by guibzo** [comment] 2024-07-22 14:00
Hi there, I got it to work, here is how:

Created in the root of the project a `fix.js` with the following code

```js
/* 
  This is used to fix a bug in Metro that prevents NativeWind from being applied on web in Windows, which crashes the compiler.
  See: https://github.com/nativewind/nativewind/pull/860
*/

// require('dotenv').config()
// console.log('EXPO_USE_METRO_WORKSPACE_ROOT:', process.env.EXPO_USE_METRO_WORKSPACE_ROOT)

const fs = require('fs')
const path = require('path')

const filePath = path.join('.', 'node_modules', 'nativewind', 'dist', 'metro', 'transformer.js')

fs.readFile(filePath, 'utf8', (err, content) => {
  if (err) {
    console.error(err)
    return
  }

  const cjsIssue = "`require('${config.nativewind.output}');`"
  const ecsIssue = "`import '${config.nativewind.output}'`"

  if (!content.includes(cjsIssue) && !content.includes(ecsIssue)) {
    return console.log('🎉 NativeWind fix already applied!')
  }

  const fix = "`require('${config.nativewind.output.replace(/\\\\/g, '\\\\\\\\')}');`"

  let updatedContent = content.replace(cjsIssue, fix)
  updatedContent = updatedContent.replace(ecsIssue, fix)

  fs.writeFile(filePath, updatedContent, 'utf8', (err) => {
    if (err) {
      return console.error(err)
    }
    console.log('🎉 NativeWind fix applied successfully!')
  })
})
```

Then I added postinstall to run it:
![image](https://github.com/user-attachments/assets/e572d428-871c-4f1e-b2af-d2f57372fb4f)

Versions are
`"nativewind": "^4.0.1",`
` "tailwindcss": "^3.4.4",`

**Comment by guibzo** [comment] 2024-07-22 14:00
Hi there, I got it to work, here is how:

Created in the root of the project a `fix.js` with the following code (thanks for someone up th

```js
/* 
  This is used to fix a bug in Metro that prevents NativeWind from being applied on web in Windows, which crashes the compiler.
  See: https://github.com/nativewind/nativewind/pull/860
*/

// require('dotenv').config()
// console.log('EXPO_USE_METRO_WORKSPACE_ROOT:', process.env.EXPO_USE_METRO_WORKSPACE_ROOT)

const fs = require('fs')
const path = require('path')

const filePath = path.join('.', 'node_modules', 'nativewind', 'dist', 'metro', 'transformer.js')

fs.readFile(filePath, 'utf8', (err, content) => {
  if (err) {
    console.error(err)
    return
  }

  const cjsIssue = "`require('${config.nativewind.output}');`"
  const ecsIssue = "`import '${config.nativewind.output}'`"

  if (!content.includes(cjsIssue) && !content.includes(ecsIssue)) {
    return console.log('🎉 NativeWind fix already applied!')
  }

  const fix = "`require('${config.nativewind.output.replace(/\\\\/g, '\\\\\\\\')}');`"

  let updatedContent = content.replace(cjsIssue, fix)
  updatedContent = updatedContent.replace(ecsIssue, fix)

  fs.writeFile(filePath, updatedContent, 'utf8', (err) => {
    if (err) {
      return console.error(err)
    }
    console.log('🎉 NativeWind fix applied successfully!')
  })
})
```

Then I added postinstall to run it:
![image](https://github.com/user-attachments/assets/e572d428-871c-4f1e-b2af-d2f57372fb4f)

Versions are
`"nativewind": "^4.0.1",`
` "tailwindcss": "^3.4.4",`

**Closed** 2024-09-02 23:08 UTC
Labels: issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:42
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
