### ISSUE TITLE
[4.1] Multiple themes not working

### ISSUE THREAD

**Issue by Bartek532** [nativewind/nativewind#1010] opened 2024-08-28 12:54 UTC
**Describe the bug**
I setup multiple themes as it's described in the docs with Expo SDK 51. However, when I'm starting my server colors aren't rendering. What's more in web version everything is working and variables are attached.

Example:

`tailwind.config.js`

```
module.exports = {
    theme: {
      colors: {
        // Create a custom color that uses a CSS custom value
        primary: "rgb(var(--color-primary) / <alpha-value>)",
      },
    },
    plugins: [
      // Set a default value on the `:root` element
      ({ addBase }) => addBase({ ":root": { "--color-primary": "0 255 0" } }),
    ],
};
```

`App.tsx`

```
import { vars } from 'nativewind'

const userTheme = vars({
  '--color-primary': '255 0 0'
});

export default App() {
  return (
    <View>
      <Text className="text-primary">Access as a theme value</Text>
      <Text className="text-[--color-primary]">Or the variable directly</Text>

      {/* Variables can be changed inline */}
      <View style={userTheme}>
        <Text className="text-primary">I am now red!</Text>
      </View>
    </View>
  )
}
```

Variables from inside the component aren't respected!
![393F1407-3524-41B5-A67B-D80131FFC20F](https://github.com/user-attachments/assets/5f273357-a1a9-4902-bc06-992365b43c98)

It's working on web:
![image](https://github.com/user-attachments/assets/7058c195-0e17-4c55-9820-9ca35fe6183b)

**Comment by marklawlor** [comment] 2024-09-02 10:04
Can you please provide a test reproduction. I'm unable to reproduce the issue with the code provided

**Comment by danstepanov** [comment] 2024-09-02 22:58
Please provide a repro in v4.1
https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue

**Comment by danstepanov** [comment] 2024-09-04 21:58
closing until there's a proper repro
https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue

**Closed by danstepanov** 2024-09-04 21:58 UTC
Labels: needs reproduction, issue-wipe-pre-v4, v4.1
