### ISSUE TITLE
Arbitrary color values do not work in Expo Snack

### ISSUE THREAD

**Issue by stesvis** [nativewind/nativewind#312] opened 2022-11-02 19:18 UTC
**Describe the bug**
`text-[custom-color-code]` and `bg-[custom-color-code]` don't seem to work.

Example:
```js
<Text className={`text-[${myColor}]`}>Some text</Text>
```
Please let me know if there is a way to use custom colors like in the tailwindcss example:
https://tailwindcss.com/docs/text-color#arbitrary-values
```html
<p class="text-[#50d71e]">
  <!-- ... -->
</p>
```

**To Reproduce**
See snack.

**Expected behavior**
Color should change.

**Expo Snack**
https://snack.expo.dev/@stesvis/hello-world

**Comment by marklawlor** [comment] 2022-11-02 23:01
Hi @stesvis

The `hardcodedTextColor` example is expected not to work as Tailwind does not support dynamically constructed classNames. It should work is `hardcodedTextColor = "text-[#ff0000]"` the full className.

The second issue is that the Expo Snack compiler has a bug where all arbitrary values are not working due to a url encoding issue.

I'll fix this soon, but you shouldn't see this issue when using it with the proper setup

**Comment by stesvis** [comment] 2022-11-03 21:42
> Hi @stesvis
> 
> The `hardcodedTextColor` example is expected not to work as Tailwind does not support dynamically constructed classNames. It should work is `hardcodedTextColor = "text-[#ff0000]"` the full className.
> 
> The second issue is that the Expo Snack compiler has a bug where all arbitrary values are not working due to a url encoding issue.
> 
> I'll fix this soon, but you shouldn't see this issue when using it with the proper setup

Thanks.

I found out more.
It works with
`hardcodedTextColor = "text-[#f00000]";`

but it doesn't work with
`const hardcodedTextColor = "text-[" + "#f00000" + "]";`

In my scenario I get the color from a variable and it seems impossible to apply it that way.
Would it be complicated to find a way to make it work?

**Comment by marklawlor** [comment] 2022-11-03 22:16
Please read https://tailwindcss.com/docs/content-configuration#troubleshooting. Tailwind doesn't do static analysis, it simply looks for the keywords in your code. It you break up the keywords into multiple strings, Tailwind cannot process them.

If you wish to style based upon a variable, you need to use CSS variables which are coming in the next major version https://github.com/marklawlor/nativewind/issues/308

**Comment by stesvis** [comment] 2022-11-03 22:21
Yes sounds good, I have a workaround anyway.
Thank you and really appreciate the package!

**Comment by stesvis** [comment] 2022-11-06 00:11
@marklawlor I found another related issue.
Not all the arbitrary text colors work.

For example this works: `<Text className="text-[#f00000]">Red</Text>`

But this one doesn't work: `<Text className="text-[#3b0f5e]">Purple</Text>`  ---> it just displays black.

Any idea why not all the color codes are applied?

**Comment by marklawlor** [comment] 2022-11-06 23:49
Please follow the troubleshooting guide https://www.nativewind.dev/guides/troubleshooting

Or update to the v3 preview #308 which resolves these issue.

**Comment by marklawlor** [comment] 2022-11-06 23:50
Arbitrary color values in Expo snack will be fixed in the v3 release

**Closed** 2024-09-02 23:10 UTC
Labels: fixed: nativewind@next, issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:16
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
