### ISSUE TITLE
[v4.1.10] Certain `classNames` do not work depending on parent components

### ISSUE THREAD

**Issue by mrzachnugent** [nativewind/nativewind#1114] opened 2024-10-05 17:57 UTC
**Describe the bug**

In the video below, a `Button` component is rendered inside a `Card` component and another `Button` is rendered outside the `Card`. They are the same `Button` so they should look exactly the same. However, they do not.

The `Button`'s text has a class name of `text-foreground` which should be black in light mode and white in dark mode.

In dark mode, the `Button`'s text in the `Card` component is black while the `Button`'s text out side the `Card` component is white.

https://github.com/user-attachments/assets/7bca1d0b-648a-4311-b208-130332911757

**Reproduction**
1. Clone https://github.com/mrzachnugent/nw-repro-v4.1.10-nested
2. Run `npm i` to install the dependencies
3. Run `npm run dev` to start the app in Expo Go in an iOS simulator
4. Toggle the theme switcher in the right side of the header while looking at the button components.

**Expected behavior**
The `Button` in the `Card` component should behave like the `Button` outside of the `Card`.

**Additional context**
This issue was brought up in react-native-reusables with v4.1.6: https://github.com/mrzachnugent/react-native-reusables/issues/247

**Comment by pedrio-gh** [comment] 2024-10-07 10:24
Happening to me too, same specs.

**Comment by koutyuke** [comment] 2024-10-07 14:51
Apparently this is caused by a css variable being passed, but the value is `null`.

**Comment by koutyuke** [comment] 2024-10-07 14:51
Also, this seems to happen with components defined elsewhere (in node_modules or monopore workspace) than in `tailwind.config.js` at the root of the project.

**Comment by koutyuke** [comment] 2024-10-08 02:57
@mrzachnugent I think we got reproducibility. Perhaps it's the `shadow`.

Try to remove all `shwdow-*` in the `Card` and see if the text-color works.

**Comment by shovel-kun** [comment] 2024-10-09 01:32
Should be related to #1097 and fixed in [@marklawlor/4.1/fix-inheritedVariables](https://github.com/nativewind/nativewind/pull/1099). 

Just patiently waiting for Nativewind 4.11 to chug along

**Comment by michelazzam** [comment] 2024-10-09 13:43
+1

**Comment by marklawlor** [comment] 2024-10-10 04:28
Fixed in `4.1.12`

**Closed by marklawlor** 2024-10-10 04:28 UTC

**Comment by eli-front** [comment] 2024-12-08 05:55
Still seeing this in `4.1.23`

**Comment by marklawlor** [comment] 2024-12-09 18:47
@eli-front Please create a new issue with a reproduction. The issue originally reported was fixed. If you still have this issue then I am unaware on how to reproduce it
