### ISSUE TITLE
.plugins is not a valid Plugin property  & i can't use nativewind V4

### ISSUE THREAD

**Issue by Bader975** [nativewind/nativewind#1184] opened 2024-11-05 16:55 UTC
**Describe the bug**

even i walked thougth docs steps and i'm getting this error

**Reproduction**
Please see our contribution guide: https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue

Please provide a reproduction of the issue using one of the following templates:
- **StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
- **Create Expo Stack template**: 
  - `npx create-expo-stack@latest --nativewind`
  - `npx create-expo-stack@latest --nativewind --expo-router`

**Expected behavior**

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
error: node_modules/expo-router/entry.js: [BABEL] /react-native/expo-app/node_modules/expo-router/entry.js: 
![image](https://github.com/user-attachments/assets/2e9a6e83-9d3c-480b-a767-eb8d5cc11e36)

![image](https://github.com/user-attachments/assets/7d934542-8430-41ad-bf92-b40fd44cc47e)

**Comment by marklawlor** [comment] 2024-11-05 21:33
We cannot troubleshoot a issue from a screenshot.

Closing issue because you failed to follow the issue template and provide a reproduction repro.

We are a team of volunteers. If you'd like support, please follow the instructions.

**Closed** 2024-11-05 21:33 UTC

**Comment by adamgajzlerowicz** [comment] 2024-11-06 08:48
Just for the record - I have the same error when upgrading. I think I have followed all the steps correctly. I reverted to version 2 for now

**Comment by adamgajzlerowicz** [comment] 2024-11-06 09:11
Update
[This issue](https://github.com/nativewind/nativewind/issues/1178) helped me.
Seems that `nativewind/babel` is now a preset, not a plugin.
