### ISSUE TITLE
Expo production build doesn't include styles in web?

### ISSUE THREAD

**Issue by Vimiso** [nativewind/nativewind#1056] opened 2024-09-10 20:03 UTC
**Describe the bug**
So I followed [this setup procedure](https://www.nativewind.dev/v4/getting-started/expo-router) for v4. All fine, styles working in web and mobile.

**Reproduction**
The problem occurs in web when testing in production using `npx expo start --no-dev --minify`. No styles are applied across the board.

**Expected behavior**
I assume some config is missing to build the main stylesheet?

**Comment by marklawlor** [comment] 2024-09-11 00:14
I created a new project using `npx create-expo-stack@latest --nativewind --expo-router`

When I run `npx expo start --no-dev --minify` my styles are applied.

I'm closing this issue as I'm unable to reproduce your issue and since no reproduction repro was provided I cannot test your issue.

**Closed by marklawlor** 2024-09-11 00:14 UTC

**Comment by Vimiso** [comment] 2024-09-11 13:43
After some time comparing the configuration options I found this was the missing piece:

`app.json`
```json
"web": {
  "bundler": "metro",
  "output": "static", <= important: added this!
  "favicon": "./assets/favicon.png"
},
```

**Comment by marklawlor** [comment] 2024-09-13 00:28
@Vimiso Spoke with Expo about this. CSS imports with non-static builds currently do not work with `--no-dev`. Its on the roadmap, but there are other issues with Expo CLI blocking this. Its also a low priority as `npx expo export` (and running the project) is the same as `--no-dev`
