### ISSUE TITLE
V4 nativewind breaks styling of react-native-collapsible-tab-view & react-native-tab-view

### ISSUE THREAD

**Issue by DaveVaval** [nativewind/nativewind#1137] opened 2024-10-14 04:47 UTC
**Describe the bug**
As the title says, nativewind breaks the styling of the TabBarItem on on at least 2 libraries that I know of:
`react-native-collapsible-tab-view`
`react-native-tab-view`

It's essentially the same issue as stated here: https://github.com/nativewind/nativewind/issues/937

I did try the fix in the replies, but the fix only works on react-native-tab-view, and doesn't change the fact that nativewind breaks the styling out of the box.

![Screenshot_20241013_235625_playground](https://github.com/user-attachments/assets/59bf7e0b-0abd-4481-83d5-be05ae53d81a)

**Reproduction**
Bug located on the tabview screen: https://github.com/DaveVaval/rn-playground

**Expected behavior**

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by danstepanov** [comment] 2024-10-15 17:49
I reopened #1039 and am closing this as a duplicate of that issue

**Closed by danstepanov** 2024-10-15 17:49 UTC
