### ISSUE TITLE
[v4.1] Expo Fast Refresh hangs for a long time when using a new utility class

### ISSUE THREAD

**Issue by valtism** [nativewind/nativewind#1044] opened 2024-09-06 03:08 UTC
**Describe the bug**
Occasionally, fast refresh will hang for a long time (~30s+) after a style has been changed. This seems to occur when it is a new utility class being used and generated by Nativewind.

**Reproduction**
If this is a known issue, let me know, but if you aren't aware of it and want a reproduction please comment and I'll put in the time towards making a reproduction on a Snack.

**Comment by valtism** [comment] 2024-09-06 03:08
This is on 4.1.6, and was also in 4.1.4

**Comment by danstepanov** [comment] 2024-09-09 20:52
Not aware of this issue, please provide a repro

**StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
**Create Expo Stack template**:
`npx create-expo-stack@latest --nativewind`
`npx create-expo-stack@latest --nativewind --expo-router`

**Comment by marklawlor** [comment] 2024-09-09 22:16
If you run the Tailwind CLI on your project `npx tailwindcss -i ./src/input.css` how long does that take to process? A very common cause of Tailwind CLI taking a long time to process is very wide `content` globs e.g. `**/*.ts` which will scan all your files, including everything inside your `node_modules`

**Comment by valtism** [comment] 2024-09-10 04:59
So I did some more digging into this, and I think I may have found the issue. @marklawlor tailwind compile was only taking ~300ms, so that wasn't the issue. Meanwhile I couldn't reproduce it on any of the templates @danstepanov linked.

I figured it must be something to do with my app configuration. The app is not very big yet, but it does use new arch.

I found that the source of the issue seemed to lie in my use of `react-native-svg-transformer`. I found that if I commented out the lines where I modified `config.transformer` and `config.resolver` the issue would disappear.

```metro.config.js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getSentryExpoConfig } = require("@sentry/react-native/metro");
const { withNativeWind } = require("nativewind/metro");

module.exports = (() => {
  // eslint-disable-next-line no-undef
  const config = getSentryExpoConfig(__dirname);

  const { transformer, resolver } = config;

  config.transformer = {
    ...transformer,
    babelTransformerPath: require.resolve("react-native-svg-transformer/expo"),
  };
  config.resolver = {
    ...resolver,
    assetExts: resolver.assetExts.filter((ext) => ext !== "svg"),
    sourceExts: [...resolver.sourceExts, "svg"],
  };

  return withNativeWind(config, { input: "./global.css" });
})();
```

So it seems like this is an issue in the interaction between these libraries in the transformer / resolver step. I'm not sure who is responsible for the slowdown in fast refresh, but it might be something to look into. 

I tried to reproduce this in an expo router CES template, but I couldn't get the same slowdown. I think this may have to do with my production app already using ~20 svg icons being transformed and a lot of classes throughout the codebase.

You might want to look into trying to replicate this on a larger codebase if you have access to it and can add the transformer, or I can open an issue in the `react-native-svg-transformer` repo if you think it's an issue coming from that side.

**Comment by marklawlor** [comment] 2024-09-10 05:09
Because you've isolated it to these functions, and they run in NodeJS, it should be fairly easy to debug either using the node inspector or by simply inserting `console.time()` statements into the JS files in the output.

For NativeWind, the relevant file is `node_modules/react-native-css-interop/dist/metro/index.js`

For the resolver, unless its the `input` file - it should just call the parent resolver

https://github.com/nativewind/nativewind/blob/main/packages/react-native-css-interop/src/metro/index.ts#L186-L192

And our transformer should only perform logic when running in a production environment

https://github.com/nativewind/nativewind/blob/c86e04b9f87acc74eb23b78c0b5003d0338002e1/packages/react-native-css-interop/src/metro/index.ts#L110-L136

But I'd stick a `console.time()` at the start and end of these functions to ensure they are not the cause of your issue. E.g if `transformOptions.dev` is not set, then it would be writing to disk somewhat often...

**Comment by valtism** [comment] 2024-09-10 05:20
Thanks for the info. It looks like `transformOptions.dev` is `true` for when I'm running this, so it's running in no time at all.

I guess this points towards `react-native-svg-transformer` being the culprit here. I'll dig around the node modules there and see if I can time a similar function on their side.

**Comment by valtism** [comment] 2024-09-10 05:31
When I add a `console.time()` to the async function inside `createTransformer` in `node_modules/react-native-svg-transformer/expo/index.js` I will usually get a couple of logs that it is running when I save a file, each timer taking ~`200`-`700`ms. It usually only runs at the start of the save, and when there is a new tailwind class being created the fast refresh generally takes ~`10`s

Still unsure where the bottleneck is happening

**Comment by marklawlor** [comment] 2024-09-10 06:38
There is one more location you could test

https://github.com/nativewind/nativewind/blob/b4dc0297a09860f9f79078ccb581f7fdc2632842/packages/react-native-css-interop/src/metro/index.ts#L241-L265

The callback function passes to `processDEV` receives the updated CSS from Tailwind CLI. This is then processes and a `change` event is emitted to Metro. It could be good to log when this function receives data and how long it takes to process it.

**Comment by valtism** [comment] 2024-09-10 23:32
That function seems to receive data only when a new classname has been generated, but it only takes a couple of ms to run

**Comment by danstepanov** [comment] 2024-09-11 22:57
@valtism Without a repro, we aren't really able to help you more. If you'd like to share your repo with us, you can but otherwise I'll close this issue for now.

**Closed by danstepanov** 2024-09-11 22:57 UTC
Labels: needs reproduction, v4.1

**Comment by valtism** [comment] 2024-09-11 23:05
@danstepanov understood. Thanks to everyone for the help trying to debug this

**Comment by pravienmangal** [comment] 2024-10-28 17:24
Hello @marklawlor, @danstepanov. I'm also facing this same problem and it's becoming an issue for our development experience at our work project.

We use Expo 51.0.38 and I introduced Nativewind to our work project by installing 4.0.1 and setup everything following the guidelines. While the integration initially worked well, I recently noticed that using new utility classes in components has resulted in Fast Refresh taking an unusually long time, sometimes over 30 seconds.

Here is the relevent configurations

**babel.config.js:**

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel"
    ]
  };
};
```

**metro.config.js:**

```
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require("nativewind/metro");

const defaultConfig = getDefaultConfig(__dirname);
defaultConfig.transformer.babelTransformerPath = require.resolve("react-native-svg-transformer");
defaultConfig.resolver.assetExts = defaultConfig.resolver.assetExts.filter(ext => ext !== "svg");
defaultConfig.resolver.sourceExts = [...defaultConfig.resolver.sourceExts, "svg"];

module.exports = withNativeWind(defaultConfig, { input: "./src/styles/global.css" });
```

Additionally, we're using file-based navigation with Expo Router and import global.css in src/app/_layout.tsx.
`import "@/styles/global.css";`

Upgrading to version 4.0.26 seemed to help, but it introduced font rendering issues. I tested subsequent versions and **4.0.36** seems to be not affecting any current styles and also resolving the refresh delay. Haven't tested it extensively though.

There are few more newer versions available with latest vesrion being 4.1.21. I tried few of the latest versions and realised if I use any versions above 4.1.0 have the same expo fast refresh hangs long time issue. So I'd be hesitant to update to latest versions. Can you please help why is this happening?

**Comment by danstepanov** [comment] 2024-10-28 17:32
No repro, can't help

**Comment by pravienmangal** [comment] 2024-10-28 22:33
Hi @danstepanov  Thank you for your response. I wanted to clarify that the issue arises when the project scales up with more components and increased usage of NativeWind. In smaller projects, everything works without issues, but as the complexity grows, the Fast Refresh delay becomes significantly noticeable.

A simple repro environment will not demonstrate the issue. I'm happy to arrange a call to discuss and showcase the problem in my setup.

**Comment by marklawlor** [comment] 2024-10-29 01:49
@pravienmangal This issue was improved in `4.1`, so I would recommend upgrading. I'm not going to go back and address `4.0` issues. In a test project of 14000 styles, on my computer, fast refresh dropped from 8s -> 1.5s

You can force TailwindCSS to generate a large number of styles by modifying your `tailwind.config.js` with a `safelist` that contains a regex

```
  safelist: [
    {
      pattern:
        /(text|background|stroke|fill)-(red|blue|green|yellow|orange|purple|slate)-(0|50|100|200|300|400|500|600|700|800|900|950)/,
    },
  ],
  ```
  
Also setting `DEBUG=nativewind` as an environment variable will log extra information in your Metro terminal, including timing.
  
At this stage I believe the compiler is working within a reasonable speed, however your issues may be caused by the styles being applied at runtime (e.g cascading and/or multiple rerenders of the new styles). This is why we will need a reproduction

**Comment by pravienmangal** [comment] 2024-10-29 09:52
Hi @marklawlor Thank you for your response and suggestions. 
I'm currently using the latest version **4.1.21** and also would like to keep the version up to date (I also follow Nativewind's twitter handle and delighted with yesterday's announcement)

I've modified the tailwind.config.js with safelist as you suggested and also set the DEBUG to check the logs. Here is the logs from my terminal

```
Android node_modules/expo-router/entry.js ░░░░░░░░░░░░░░░░  0.0% (0/1)  nativewind getTransformOptions.dev true +6s
  nativewind getTransformOptions.platform android +0ms
  nativewind getTransformOptions.virtualModulesPossible true +0ms
  nativewind virtualModules /Users/pravienmangal/Development/WSCrew/node_modules/react-native-css-interop/.cache/android.js +1ms
  nativewind virtualModules.isDev true +0ms
  nativewind virtualModules.size 0 +0ms
  nativewind virtualModules.fastRefresh enabled +0ms
  nativewind getCSSForPlatform: android +7s
  nativewind Start development Tailwind CLI +0ms
  nativewind getTransformOptions.writeToFileSystem false +1ms
  nativewind resolveRequest.input /Users/pravienmangal/Development/WSCrew/src/styles/global.css +99ms
  nativewind resolveRequest.resolvedTo: /Users/pravienmangal/Development/WSCrew/node_modules/react-native-css-interop/.cache/android.js +0ms
  nativewind resolveRequest.development: true +0ms
  nativewind resolveRequest.platform: android +0ms


Android node_modules/expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.9% (2017/2018)  nativewind Finished initial development Tailwind CLI +817ms
  nativewind virtualStyles.initial android +717ms
  nativewind Start stringify +92ms
  nativewind Output size: 365923 bytes +19ms
Android Bundled 1000ms node_modules/expo-router/entry.js (2018 modules)
  nativewind Tailwind CLI detected new styles +52s
  nativewind virtualStyles.update android +52s
  nativewind Start stringify +200ms
  nativewind Output size: 365991 bytes +28ms
  nativewind virtualStyles.emit android +0ms
```
  
I reviewed the debug logs and noticed that the Tailwind CLI takes an unusually long time to detect new styles, specifically showing +52s in the logs. The output size of the styles is around 365,000 bytes, which might be contributing to the delays.

I am actively working to refine my safelist and reduce the number of styles generated. If you have any additional suggestions or optimizations in light of this information, I would greatly appreciate your input.

Thank you for your continued support!

**Comment by marklawlor** [comment] 2024-10-30 06:11
That safe list is for generating a reproduction repro if you are unable to share your current project. Adding to a problem project will cause it to slow down even more due to the sheer number of styles. 

I would really appreciate if you provided a reproduction repro, that way I can directly fix your issue. Otherwise I'm just guessing what the problem is and I'm most likely going to end up fixing other problems, and not the one that's causing you grief.

**Comment by pravienmangal** [comment] 2024-10-30 13:53
@marklawlor In that case, I'll see if I can mock up something to reproduce the issue and get back to you

**Comment by luffy-taro** [comment] 2025-02-05 06:05
In debug mode, I get following output

```
 nativewind Tailwind CLI detected new styles +2m
  nativewind virtualStyles.update android +2m
  nativewind Start stringify +24ms
  nativewind Output size: 14028 bytes +5ms
  nativewind virtualStyles.emit android +0ms
```

After which it shows "refreshing..." at the top and takes 20sec before rendering.

**Comment by luffy-taro** [comment] 2025-02-05 06:31
As @pravienmangal mentioned, downgrading to `4.0.26` fixes this issue, and changes are instantaneous.

**Comment by pravienmangal** [comment] 2025-02-05 10:58
@luffy-taro this downgrade fix will just be a temporary fix. After a little while you'll probably face the same issue just as we are still facing the same issue with 4.0.26 or 4.0.36. I didn't have the chance to setup a repro yet as I'm busy with project work, but will do it at some point so that the Nativewind team can take a look

**Comment by luffy-taro** [comment] 2025-02-05 12:18
I was not able to reproduce this. I tried a demo app and put in SVG icon as well using `react-native-svg-transformer` but no luck.

**Comment by pravienmangal** [comment] 2025-02-05 12:42
I just tried as well and as @marklawlor suggested I Included the safelist in the `tailwind.config`, but couldn't reproduce this issue. So don't see a repro will help any of us at this point.
@marklawlor or @danstepanov happy to have a call with you to discuss this
`safelist: [
    {
      pattern:
        /(text|background|stroke|fill)-(red|blue|green|yellow|orange|purple|slate)-(0|50|100|200|300|400|500|600|700|800|900|950)/,
    },
  ],`

**Comment by luffy-taro** [comment] 2025-02-08 14:26
```
 +2mpo:start:interface:keyPressHandler Key pressed:
  expo:start:interface:keyPressHandler Key pressed:
 +8s
  nativewind Tailwind CLI detected new styles +2m
  nativewind virtualStyles.update android +2m
  react-native-css-interop Features {"transformPercentagePolyfill":true,"disableGapPercentageValues":true,"disableDisplayBlock":false,"disableAlignContentEvenly":false,"disablePositionStatic":false} +0ms
  react-native-css-interop Grouping /^group(\/.*)?/ +0ms
  react-native-css-interop Start lightningcss +0ms
  react-native-css-interop Found 217 rules to process +9ms
  react-native-css-interop Exiting lightningcss +7ms
  react-native-css-interop Found 204 valid rules +1ms
  nativewind Start stringify +18ms
  nativewind Output size: 14094 bytes +4ms
  nativewind virtualStyles.emit android +0ms
  Metro:DeltaCalculator Handling change: C:\Users\me\code\myapp\node_modules\react-native-css-interop\.cache\android.js (type: virtual) +2m
  expo:start:server:metro:metroWatchTypeScriptFiles Detected TypeScript file changed in the project:  C:\Users\me\code\myapp\app\(app)\(tabs)\workorders.tsx +2m
  Metro:DeltaCalculator Handling change: C:\Users\me\code\myapp\app\(app)\(tabs)\workorders.tsx (type: f) +2ms
  Metro:DeltaCalculator Calculating delta (reset: false, shallow: false) +61ms
  Metro:DeltaCalculator Traversing dependencies for 2 paths +1ms
  expo:metro:tsconfig-paths @/components/headers/HeaderWithBackNav -> C:\Users\me\code\myapp\components\headers\HeaderWithBackNav +2m
  expo:metro:tsconfig-paths @/components/FabButton -> C:\Users\me\code\myapp\components\FabButton +1ms
  expo:metro:tsconfig-paths @/api/hooks/useWorkorders -> C:\Users\me\code\myapp\api\hooks\useWorkorders +0ms
  expo:metro:tsconfig-paths @/components/workorders/FiltersBottomSheet -> C:\Users\me\code\myapp\components\workorders\FiltersBottomSheet +0ms
  expo:metro:tsconfig-paths @/components/CustomInput -> C:\Users\me\code\myapp\components\CustomInput +1ms
  expo:metro:tsconfig-paths @/components/ui/Button -> C:\Users\me\code\myapp\components\ui\Button +0ms
  expo:metro:tsconfig-paths @/constants/icons -> C:\Users\me\code\myapp\constants\icons +0ms
  expo:metro:tsconfig-paths @/components/workorders/SortByFilterBottomSheet -> C:\Users\me\code\myapp\components\workorders\SortByFilterBottomSheet +0ms
  expo:metro:tsconfig-paths @/components/workorders/NoWorkorders -> C:\Users\me\code\myapp\components\workorders\NoWorkorders +1ms
  expo:metro:tsconfig-paths @/components/workorders/helpers -> C:\Users\me\code\myapp\components\workorders\helpers +0ms
  expo:metro:tsconfig-paths @/utils -> C:\Users\me\code\myapp\utils +1ms
  expo:metro:tsconfig-paths @/components/ui/Badge -> C:\Users\me\code\myapp\components\ui\Badge +1ms
  expo:metro:tsconfig-paths @/hooks/useRefreshOnFocus -> C:\Users\me\code\myapp\hooks\useRefreshOnFocus +0ms
  expo:metro:tsconfig-paths @/components/workorders/WorkOrderItem -> C:\Users\me\code\myapp\components\workorders\WorkOrderItem +1ms
  Metro:DeltaCalculator Calculated graph delta {added: 0, modified: 2, deleted: 0} +130ms

  // 30 second pause
  LOG  Rendering WorkOrders
```

I have tried setting DEBUG="*" (minus babel logs) but nothing that stands out. There's a 20-30 seconds delay after which it renders the component. 

It's faster to simply reload the app and see the result.

**Comment by luffy-taro** [comment] 2025-02-11 14:10
Not sure if this is helpful but this is what I get in javascript profiler. 

![Image](https://github.com/user-attachments/assets/ad8a13c8-7546-49d9-8dae-1df5bccb9b83)

**Comment by luffy-taro** [comment] 2025-02-11 14:51
I have narrowed it down to this [line](https://github.com/nativewind/nativewind/blob/79b5cce729696f41f43ac5ae602c52c576d558ff/packages/react-native-css-interop/src/runtime/native/styles.ts#L218)

```
  if (value) {
      const now = performance.now();
      value.set(style);
      console.log(`[css-interop] Style update time: ${performance.now() - now}ms ${name}` );
  } else {
      const now = performance.now();
      styles.set(name, (0, observable_1.observable)(style));
      console.log(`[css-interop] Style insert time: ${performance.now() - now}ms`);
  }
```

It only happens at the first `value.set`. Below is log after I added style like `bg-brown-950` to a view. 

```
 LOG  [css-interop] Style update time: 26.674699999857694ms h-full
 LOG  [css-interop] Style update time: 1375.1714999997057ms flex-1
 LOG  [css-interop] Style update time: 68.0893999999389ms bg-white
 LOG  [css-interop] Style update time: 1292.2328000003472ms gap-4
 LOG  [css-interop] Style update time: 79.40529999975115ms px-5
 LOG  [css-interop] Style update time: 21.501000000163913ms bg-yellow-900
 LOG  [css-interop] Style update time: 1624.3229000000283ms flex
 LOG  [css-interop] Style update time: 6705.910099999979ms flex-row
 LOG  [css-interop] Style update time: 5567.652799999807ms items-center
 LOG  [css-interop] Style update time: 1357.2620999999344ms justify-between
 LOG  [css-interop] Style update time: 20.289600000251085ms h-10
 LOG  [css-interop] Style update time: 43.76110000023618ms mt-4
 LOG  [css-interop] Style update time: 1333.1504000001587ms text-base
 LOG  [css-interop] Style update time: 24.3835999998264ms font-semibold
 LOG  [css-interop] Style update time: 42.7355999997817ms leading-6
 LOG  [css-interop] Style update time: 20.24629999976605ms text-center
 LOG  [css-interop] Style update time: 65.63870000001043ms text-gray-900
 LOG  [css-interop] Style update time: 21.52210000017658ms h-12
 LOG  [css-interop] Style update time: 272.496799999848ms bg-gray-100
 LOG  [css-interop] Style update time: 1309.279699999839ms rounded-md
 LOG  [css-interop] Style update time: 21.847099999897182ms overflow-hidden
 LOG  [css-interop] Style update time: 21.349099999759346ms px-3
 LOG  [css-interop] Style update time: 26.367500000167638ms relative
 LOG  [css-interop] Style update time: 1517.5529000000097ms gap-2
 LOG  [css-interop] Style update time: 23.192100000102073ms fill-gray-700
 LOG  [css-interop] Style update time: 187.94389999983832ms font-normal
 LOG  [css-interop] Style update time: 1515.842399999965ms justify-center
 LOG  [css-interop] Style update time: 157.98549999995157ms mt-1
 LOG  [css-interop] Style update time: 161.68610000004992ms leading-[14.4px]
 LOG  [css-interop] Style update time: 4150.2683000001125ms text-xs
 LOG  [css-interop] Style update time: 20.55269999988377ms text-sm
 LOG  [css-interop] Style update time: 24.549300000071526ms font-medium
 LOG  [css-interop] Style update time: 64.02659999998286ms gap-1
 LOG  [css-interop] Style update time: 46.637800000142306ms px-4
 LOG  [css-interop] Style update time: 2635.646499999799ms py-1
 LOG  [css-interop] Style update time: 49.29950000019744ms h-8
 LOG  [css-interop] Style update time: 4032.4503999999724ms rounded-full
 LOG  [css-interop] Style update time: 1339.6984000001103ms border
 LOG  [css-interop] Style update time: 43.602100000251085ms border-gray-400
 LOG  [css-interop] Style update time: 46.137100000400096ms h-5
 LOG  [css-interop] Style update time: 43.62140000006184ms w-5
 LOG  [css-interop] Style update time: 22.538100000005215ms absolute
 LOG  [css-interop] Style update time: 26.059099999722093ms h-14
 LOG  [css-interop] Style update time: 23.433999999891967ms w-14
 LOG  [css-interop] Style update time: 22.34690000023693ms bg-primary
 LOG  [css-interop] Style update time: 26.051400000229478ms right-4
 LOG  [css-interop] Style update time: 22.806799999903888ms bottom-4
 LOG  [css-interop] Style update time: 23.300100000109524ms text-white
 LOG  [css-interop] Style update time: 1353.8253000001423ms p-4
 LOG  [css-interop] Style update time: 1296.217900000047ms rounded-lg
 LOG  [css-interop] Style update time: 1289.2412999998778ms border-gray-300
 LOG  [css-interop] Style update time: 1277.3809999995865ms border-[0.5px]
 LOG  [css-interop] Style update time: 2706.838999999687ms h-[72px]
 LOG  [css-interop] Style update time: 1372.2069000001065ms w-[72px]
 LOG  [css-interop] Style update time: 1456.2957000001334ms mr-4
 LOG  [css-interop] Style update time: 2842.8707000003196ms font-bold
 LOG  [css-interop] Style update time: 1430.0211000000127ms text-gray-500
 LOG  [css-interop] Style update time: 1195.7450000001118ms bg-blue-100
 LOG  [css-interop] Style update time: 2805.054899999872ms px-2
 LOG  [css-interop] Style update time: 1288.1096000000834ms text-blue-600
 LOG  [css-interop] Style update time: 278.87550000008196ms text-gray-600
 LOG  [css-interop] Style update time: 1389.37229999993ms w-6
 LOG  [css-interop] Style update time: 1362.467499999795ms h-6
 LOG  [css-interop] Style update time: 1360.7851999998093ms -ml-2
 LOG  [css-interop] Style update time: 1392.8268999997526ms border-white
 LOG  [css-interop] Style update time: 1403.7170000001788ms text-black
 LOG  [css-interop] Style update time: 1330.629300000146ms h-4
 LOG  [css-interop] Style update time: 1065.5322000002488ms bg-yellow-100
 LOG  [css-interop] Style update time: 1002.6598999998532ms text-yellow-600
 LOG  [css-interop] Style update time: 278.5908999997191ms bg-red-100
 LOG  [css-interop] Style update time: 276.9303000001237ms text-red-600
 LOG  [css-interop] Style update time: 59.43999999994412ms bg-green-100
 LOG  [css-interop] Style update time: 62.100700000301ms text-green-600
 LOG  [css-interop] Data injected in 69186.64449999994ms
```

**Comment by luffy-taro** [comment] 2025-04-11 18:22
Not sure how but this problem went away after some time, may be upgrade to SDK 52 did it or may be earlier code was breaking some fast refresh rules. I was away from my current project so couldn't debug.
