### ISSUE TITLE
V4.1: ScrollView indicatorStyle prop causing "TypeError: right operand of 'in' is not an object"

### ISSUE THREAD

**Issue by pstruschka** [nativewind/nativewind#1054] opened 2024-09-10 08:54 UTC
**Describe the bug**
ScrollView indicatorStyle prop throwing an error. Same error as #1012

**Reproduction**
- nativewind@4.1.7 (nativewind@next)

Create ScrollView with indicatorStyle prop
```tsx
<ScrollView indicatorStyle={'white'}></ScrollView>
```
https://stackblitz.com/edit/nativewind-test-vfyfwd?file=nativewind.test.tsx

**Additional context**
![image](https://github.com/user-attachments/assets/43ddd323-9cb6-438c-8cb9-50c876b43bf2)

**Comment by danstepanov** [comment] 2024-09-18 02:20
This is still an issue in 4.1.10

**Comment by hirbod** [comment] 2024-09-27 16:48
Oh, just ran into this.

**Comment by koutyuke** [comment] 2024-10-03 14:27
Could [this line](https://github.com/nativewind/nativewind/blob/8e319604350dafe61d16eb2557c797ae168b4e74/packages/react-native-css-interop/src/runtime/components.ts#L43) be the cause of this?

**Comment by koutyuke** [comment] 2024-10-03 14:32
I don't think indicatorStyle is a property for style.

https://reactnative.dev/docs/scrollview#indicatorstyle-ios

**Comment by hirbod** [comment] 2024-10-04 09:37
I am pretty sure you found the source of problem @koutyuke
indicatorStyle is indeed not a property of style and thus should not be remapped to a style

**Comment by koutyuke** [comment] 2024-10-11 09:15
fixed by [this commit](https://github.com/nativewind/nativewind/commit/b117d6599d985ad1141acf5510a02a7c8ff26f6e)

**Comment by hirbod** [comment] 2024-10-11 12:35
It's not fully fixed. Still happens for FlatList for example. was only partially fixed.

**Comment by danstepanov** [comment] 2024-10-15 18:16
@hirbod can you provide a flatlist repro? https://nativewind.dev/issue

**Comment by danstepanov** [comment] 2024-10-25 20:51
@hirbod If this isn't fixed, I'll look into removing `indicatorStyle` for FlatList as well

**Comment by danstepanov** [comment] 2024-10-25 20:52
repro is still needed

**Comment by danstepanov** [comment] 2024-10-25 20:52
and actually, it should be a separate issue, i'm closing this one

**Closed by danstepanov** 2024-10-25 20:52 UTC
Labels: bug, needs reproduction, v4.1

**Comment by hirbod** [comment] 2024-10-25 21:49
It was fixed meanwhile, all good!
