### ISSUE TITLE
Can't define custom font sizes

### ISSUE THREAD

**Issue by fmcalado** [nativewind/nativewind#369] opened 2022-12-18 18:59 UTC
**Describe the bug**
When trying to define custom font sizes for different devices dpi, it doesn't compile.

index.js: [BABEL] C:\Users\conta\Desktop\Dev\my-proj\index.js: Cannot use import statement outside a module (While processing: "C:\\Users\\conta\\Desktop\\Dev\\my-proj\\node_modules\\nativewind\\babel.js")

**To Reproduce**
1. Use nativewind ^2.0.11
2. Go to tailwind.config.js
3. Import const { fontScale } = require("nativewind");
4. Define any custom fontSizes using fontScale
5. Use the class on any Text component
6. See error

**Comment by fendyk** [comment] 2022-12-19 12:26
Can you send us your whole `tailwind.config.js` file?

**Comment by fmcalado** [comment] 2022-12-19 12:41
```js
/** @type {import('tailwindcss').Config} */
const { fontScale } = require('nativewind');

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          200: '#e5f3ff',
          500: '#0083FF',
          600: '#0062bf',
          900: '#004280',
        },
        gray: {
          base: '#C2C9D1',
          100: '#f0f1f3',
          200: '#d6d6d6',
          300: '#91979d',
          500: '#707070',
          600: '#616569',
        },
        error: {
          500: '#ff3133',
        },
      },
      boxShadow: {
        elevation: '0px 2px 4px rgba(0, 0, 0, 0.24)',
        isometric: '0px 4px 4px rgba(0, 0, 0, 0.25)',
      },
      fontFamily: {
        openSansSemiBold: 'OpenSans_600SemiBold',
        openSansRegular: 'OpenSans_400Regular',
      },
      backgroundImage: {
        grad: 'linear-gradient(0deg, rgba(255, 255, 255, 0.9), rgba(255, 255, 255, 0.9)), #C2C9D1;',
      },
      fontSize: {
        custom: [fontScale(20), fontScale(28)]
      }
    },
  },
  plugins: [],
};```

**Comment by fmcalado** [comment] 2022-12-19 12:43
Text example: 
```js
<Text className='mb-2 font-openSansSemiBold text-custom'>
    Oi, {FAKE_USERNAME}
</Text>
```

**Comment by fendyk** [comment] 2022-12-19 13:08
You're using `fontScale()` which is only available in `3.0.0`. In older functions (the one you're using is `2.0.11`), use `getFontScale()`

First require:
```
const { getFontScale } = require("nativewind");
```

Then do the following:
```
fontSize: {
  number: fontScale(20)
  object: fontScale({
    1: 10
    1.5: 15
    2: 20
  })
```
Source: https://www.nativewind.dev/customization/theme#fontscale

**Comment by fmcalado** [comment] 2022-12-19 16:52
> You're using `fontScale()` which is only available in `3.0.0`. In older functions (the one you're using is `2.0.11`), use `getFontScale()`
> 
> First require:
> 
> ```
> const { getFontScale } = require("nativewind");
> ```
> 
> Then do the following:
> 
> ```
> fontSize: {
>   number: fontScale(20)
>   object: fontScale({
>     1: 10
>     1.5: 15
>     2: 20
>   })
> ```
> 
> Source: https://www.nativewind.dev/customization/theme#fontscale

Have already tried it, didn't work. Also, there's inconsistency on the docs, as it requires `getFontScale` but uses `fontScale`.
Although I've tried both ways and none of them worked.

**Comment by fendyk** [comment] 2022-12-20 07:55
> > You're using `fontScale()` which is only available in `3.0.0`. In older functions (the one you're using is `2.0.11`), use `getFontScale()`
> > First require:
> > ```
> > const { getFontScale } = require("nativewind");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then do the following:
> > ```
> > fontSize: {
> >   number: fontScale(20)
> >   object: fontScale({
> >     1: 10
> >     1.5: 15
> >     2: 20
> >   })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Source: https://www.nativewind.dev/customization/theme#fontscale
> 
> Have already tried it, didn't work. Also, there's inconsistency on the docs, as it requires `getFontScale` but uses `fontScale`. Although I've tried both ways and none of them worked.

Also tried to clear your cache and node_modules?

**Comment by fendyk** [comment] 2022-12-20 07:56
Did you try to clear your cache and node_modules?

**Comment by artieeg** [comment] 2022-12-21 14:31
Hey, had the same problem, you need to import it like this (for nativewind 2):

```
const {fontScale} = require('nativewind/dist/theme-functions')
```

Simple `require('nativewind')` won't work unfortunately

**Comment by fmcalado** [comment] 2022-12-22 11:17
> Hey, had the same problem, you need to import it like this (for nativewind 2):
> 
> ```
> const {fontScale} = require('nativewind/dist/theme-functions')
> ```
> 
> Simple `require('nativewind')` won't work unfortunately

It worked

**Comment by artieeg** [comment] 2022-12-22 13:38
@fmcalado can you confirm this function is working correctly for you? 

For me, it seems to return the same value for iPhone SE and iPhone 14 both on the actual device and simulator, I tried both `fontScale` and `pixelScale` functions

I ended up implementing font scale on the component level, and I am going to migrate to nativewind@3.0.0 when it's ready

**Comment by fmcalado** [comment] 2022-12-22 13:40
> 

It didn't seem to have any real effect but i thought it was just my eyes tricking me.
Can you show me an example of how u scaled it on a component level?

**Comment by artieeg** [comment] 2022-12-22 13:54
Sure, it work something like this

```
// Details: https://reactnative.dev/docs/pixelratio#get
const MEDIUM = 3;
const SMALL = 2;

export function getScaledValue(
  value: Record<typeof SMALL | typeof MEDIUM, number>,
) {
  const data = {
    ...value,
    1: value[SMALL],
    1.5: value[SMALL],
    3.5: value[MEDIUM],
  };

  return data[Dimensions.get('window').scale as keyof typeof data];
}

export const scaledLineHeight = {
  xl: getScaledValue({
    [MEDIUM]: 34,
    [SMALL]: 28,
  }),
  lg: getScaledValue({
    [MEDIUM]: 22,
    [SMALL]: 20,
  }),
};

export const scaledFontSize = {
  xl: getScaledValue({
    [MEDIUM]: 28,
    [SMALL]: 22,
  }),

  lg: getScaledValue({
    [MEDIUM]: 17,
    [SMALL]: 15,
  }),
};
```

I have a custom `Text` component that receives a variant prop

Based on that `variant` prop I apply tailwind classNames (I have an object [variantName]: "... tailwind classes..."

For certain `variant` values I also apply custom styles

```
const customStyles: Partial<Record<TextVariant, StyleProp<TextStyle>>> = {
  'onboarding-title': {
    fontSize: scaledFontSize.xl,
    lineHeight: scaledLineHeight.xl,
  },
  // ....
}
```

Probably not the best approach to do things, but works for now, I hope it will be fixed in nativewind@3 so I can handle font scaling within `tailwind.config.js`

**Comment by semvgelooven** [comment] 2023-04-28 12:04
When using V3 you need to use:

`const { fontScale } = require("nativewind/theme");` in your `tailwind.config.js` file.

**Comment by pixelkoduje** [comment] 2023-06-26 10:03
I need to be able to change the base fontSize dynamically. How to do it and whether is it possible? After clicking, for example, on a button.

**Closed** 2024-09-02 23:10 UTC
Labels: issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:16
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
