### ISSUE TITLE
[v4] ring doesnt seem to work

### ISSUE THREAD

**Issue by asktree** [nativewind/nativewind#954] opened 2024-06-24 22:01 UTC
Tailwind's `ring` class doesn't appear to do anything (when attached to a View, anyway). I checked and verified that the output.css contains the right classes. Is this a known issue?

**Comment by ceopaludetto** [comment] 2024-06-28 15:01
Ring properties are marked as web-only in the docs https://www.nativewind.dev/v4/tailwind/borders/ring-width

**Comment by PetarMarijanovic** [comment] 2024-07-07 21:55
Is there an equivalent?

**Comment by ceopaludetto** [comment] 2024-07-12 13:45
> Is there an equivalent?

I don't think so, but @marklawlor or @danstepanov can answer better

**Closed** 2024-09-02 23:08 UTC
Labels: issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:35
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
