### ISSUE TITLE
color is not applied when using a variable

### ISSUE THREAD

**Issue by sgwanlee** [nativewind/nativewind#1149] opened 2024-10-17 01:23 UTC
**Describe the bug**
I declared colors as a variable like the below
```
export const actionColors = {
  [Action.WALK]: { bg: "bg-red-400", text: "text-red-400" },
  [Action.PLAY]: { bg: "bg-blue-400", text: "text-blue-400" },
  [Action.FOOD]: { bg: "bg-green-400", text: "text-green-400" },
  [Action.NAP]: { bg: "bg-yellow-400", text: "text-yellow-400" },
  [Action.DIAPER]: { bg: "bg-purple-400", text: "text-purple-400" },
  [Action.BEAUTY]: { bg: "bg-orange-400", text: "text-orange-400" },
  [Action.BATH]: { bg: "bg-pink-400", text: "text-pink-400" },
};

```

so I expected to see background color is applied based on the action
```
<TouchableOpacity
  key={item.id}
  onPress={() => handleActionPress(item.action)}
  className={`px-4 rounded-full items-center justify-center ${item.bgColor}`}
>
  <Text className="text-white font-bold">{item.title}</Text>
</TouchableOpacity>
```

but background colors are not applied. and when I added dummy `View` component like the below, only then I can see background colors applied
```
<View
  className={cn(
    "h-0 w-0",
    "bg-purple-400 bg-green-400 bg-orange-400 bg-pink-400 bg-yellow-400",
    "text-purple-400 text-green-400 text-orange-400 text-pink-400 text-yellow-400"
  )}
/>
```

**Comment by ioss** [comment] 2024-10-21 19:06
Probably the file containing your `export const actionColors = ...` is not covered by your `tailwind content` path(es).
Make sure that all files having tailwind classes are found by the content configuration.

(Like for example `actionColors` is in a file with a `.ts` extension, but maybe your content configuration searches only for files with `.tsx`?)

**Comment by marklawlor** [comment] 2024-10-21 22:46
Please follow the issue template and provide all required information - at the minimum a reproduction repro.

I cannot provide answer without seeing your code. The issue is most likely not in the snippets you linked but else where in the project.

I'm closing this issue due to lack of information. Please create a new issue and follow the template if you wish to recieve support.

**Closed by marklawlor** 2024-10-21 22:46 UTC
