### ISSUE TITLE
setColorScheme (Dark Mode) is broken

### ISSUE THREAD

**Issue by enchorb** [nativewind/nativewind#913] opened 2024-05-12 15:27 UTC
Further described in this issue: https://github.com/marklawlor/nativewind/issues/866

Once either `dark` or `light` is set then further system settings changes what trigger an update

Setting `system` also doesn't work (if you toggle dark mode in device settings the app ui doesn't update).

Even if dark/light is set in `setColorScheme`, system (device) changes should still trigger.

**Comment by tarifalhasan** [comment] 2024-05-13 03:11
I'm facing the same issue. did you fixed

**Comment by desiboli** [comment] 2024-05-20 09:09
I was having problem with the dark mode functionality in my app as well and I found out that I by accident changed the .dark selector in global.css from `.dark:root` to `.dark`. Hopefully this can help someone else!

**Comment by danstepanov** [comment] 2024-05-30 15:05
Closed as duplicate of #917

**Closed by danstepanov** 2024-05-30 15:05 UTC

**Comment by enchorb** [comment] 2024-05-30 15:12
@danstepanov condering both tickets are closed should a new ticket be opened to have Nativeiwnd work with the latest Tailwind release?

**Comment by danstepanov** [comment] 2024-05-30 15:14
@enchorb That would be a separate concern, yes.
