### ISSUE TITLE
[v4.1] Attempted import error: 'createElement' is not exported from 'nativewind' (imported as '_createElement')

### ISSUE THREAD

**Issue by divineniiquaye** [nativewind/nativewind#1115] opened 2024-10-05 21:49 UTC
This error happens when I use `react-native-calendars` in nextjs 14 with nativewind.

Here's my next.config.js config:

```js
const { withExpo } = require("@expo/next-adapter");

/** @type {import('next').NextConfig} */
const nextConfig = {
    reactStrictMode: false,
    transpilePackages: [
        "@react-native/assets-registry",
        "@repo/ui",
        "expo",
        "expo-asset",
        "expo-constants",
        "expo-font",
        "expo-modules-core",
        "expo-status-bar",
        "nativewind",
        "react-native-calendars",
        "react-native-css-interop",
        "react-native",
        "react-native-gesture-handler",
        "react-native-reanimated",
        "react-native-swipe-gestures",
        "react-native-safe-area-context",
        "react-native-web",
        "solito",
    ],
    images: {
        remotePatterns: [
            {
                protocol: "https",
                hostname: "play.google.com",
            },
            {
                protocol: "https",
                hostname: "developer.apple.com",
            },
        ],
    },
    webpack: (config) => {
        config.resolve.alias = {
            ...(config.resolve.alias || {}),
            // Transform all direct `react-native` imports to `react-native-web`
            "react-native$": "react-native-web",
        };
        // config.resolve.extensions = [
        //     ".web.js",
        //     ".web.jsx",
        //     ".web.ts",
        //     ".web.tsx",
        //     ...config.resolve.extensions,
        // ];
        return config;
    },
};

module.exports = withExpo(nextConfig);
```

And here is the error:

```
Attempted import error: 'createElement' is not exported from 'nativewind' (imported as '_createElement').
web:dev: 
web:dev: Import trace for requested module:
web:dev: ../../node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
web:dev: ../../node_modules/react-native-calendars/src/index.ts
web:dev: ../../packages/ui/themed/calender/index.tsx
web:dev: ./app/page.tsx
web:dev: 
web:dev: ../../node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
web:dev: Attempted import error: 'createElement' is not exported from 'nativewind' (imported as '_createElement').
web:dev: 
web:dev: Import trace for requested module:
web:dev: ../../node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
web:dev: ../../node_modules/react-native-calendars/src/index.ts
web:dev: ../../packages/ui/themed/calender/index.tsx
web:dev: ./app/page.tsx
```

**Comment by marklawlor** [comment] 2024-10-08 00:20
Are you able to provide a full reproduction that I'm able to run? [`createElement` is being exported](https://github.com/nativewind/nativewind/blob/979f3bfed17fecbaaaa0dda0dbe436a892c0c29f/packages/nativewind/src/index.tsx#L16), so I would need to run/build the project to investigate further

**Comment by divineniiquaye** [comment] 2024-10-08 22:50
@marklawlor  I've reproduced the issue in this repo https://github.com/divineniiquaye/nativewind-issue-1115.

Command: `pnpm install && pnpm run dev`
Visit https://localhost:300 to log the error.

**Comment by marklawlor** [comment] 2024-10-09 06:03
Can you please provide a simpler reproduction repro, preferably one that is the NextJS starter template, isn't a monorepro and isn't using pnpm.

Please note that NextJS is not an officially supported bundler and I am not familiar with NextJS. I'm not saying that I won't investigate and try and provide support, but I need the production to be smaller otherwise I'm spending more time learning about how NextJS works than actually fixing your issue.

**Comment by divineniiquaye** [comment] 2024-10-13 11:40
I've removed all the monorepo stuff, It's now just a nextjs app with expo and nativewind, am unable to get yarn to work on my repo, please kindly try and use pnpm since it's just a package manager.

The issue is reproduced in the  [next branch](https://github.com/divineniiquaye/nativewind-issue-1115/tree/next)

**Comment by marklawlor** [comment] 2024-10-22 07:31
@divineniiquaye A minimal app is the nextjs starter template with NativeWind added.

This is a free open source project, any time I spend here is my own free time. I do not have enough time to learn about each individual setup. Hence I need a minimal repro or the problem isolated.

To help you isolate the issue, I cloned your repro and reset it back to a state where NativeWind is working https://github.com/marklawlor/nativewind-issue-1115

I would recommend comparing these two projects to isolate where the problem issue is. Once identified I can help you with a resolution.

**Comment by danstepanov** [comment] 2024-10-25 20:41
closing this for now as there is no repro or request for something from us

**Closed by danstepanov** 2024-10-25 20:41 UTC

**Comment by divineniiquaye** [comment] 2024-10-27 20:31
@marklawlor It's working now in version v4.1.21
