### ISSUE TITLE
dark class toggle not working on web

### ISSUE THREAD

**Issue by vktrl** [nativewind/nativewind#882] opened 2024-04-16 10:38 UTC
Setting dark mode in the browser results in `undefined` being added as a class instead of `dark`. This happens both when using `colorScheme.toggle()`, `colorScheme.set("dark")` and methods from `useColorScheme`. It works fine on native.

I haven't found a way to reliably replicate this behavior. I've moved code verbatim from one repo to another but it's inconsistent. The only clue I have is that the class being set is `undefined`, but I haven't tracked down the potential cause in the codebase and I'm not very familiar with RN. For now I'm handling the class toggle manually.

PNPM monorepo
Nativewind 4.0.36
Tailwind 3.4.1

**Comment by danstepanov** [comment] 2024-05-30 15:04
Closed as duplicate of #917

**Closed by danstepanov** 2024-05-30 15:04 UTC
