### ISSUE TITLE
[v4] Merging style and className when using cssInterop not working

### ISSUE THREAD

**Issue by focux** [nativewind/nativewind#957] opened 2024-06-28 19:26 UTC
When using `cssInterop`, and you pass the component a `style` and `className`, I would expect the styles to be merged but looks like it's not the case. My use case it's passing both style and className to ExpoImage. I'm computing the images size dynamically so I can't use a className for the size but I do want to keep using tailwind for other properties.

My work-around is to only allow a `style` or className to be passed down to the component:

```ts
const ImageComponent = ({
  style,
  $style,
  ...props
}: ImageProps & { $style?: StyleProp<ImageStyle> }) => {
  // TODO - i'm still not sure how to merge these styles
  if (style && $style) throw new Error("Pass either a className or style prop, not both");

  return <ExpoImage style={[style, $style]} {...props} />;
};

export const Image = cssInterop(ImageComponent, {
  className: "$style",
});
```

**Comment by DanielGiljam** [comment] 2024-08-26 05:44
Expected behavior is that style and className is merged, but they are not? What happens instead when you pass both style and className?

**Closed** 2024-09-02 23:08 UTC
Labels: issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:47
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
