### ISSUE TITLE
SVG: dark mode

### ISSUE THREAD

**Issue by Gregoirevda** [nativewind/nativewind#435] opened 2023-03-09 20:18 UTC
**Describe the bug**
Applying className on `react-native-svg` icons works well
```jsx
<Icon className="text-black" />
```

but not when used with dark mode
```jsx
<Icon className="text-black dark:text-white" />
````

An error appears when it needs to [extract props](https://github.com/software-mansion/react-native-svg/blob/main/src/elements/G.tsx#L39) from the `G` tag.

It fails at [mask.match](https://github.com/software-mansion/react-native-svg/blob/main/src/lib/extract/extractProps.ts#L131) is not a function because match is not a string, but the number `1`

I have debugged nativewind and came to the conclusion that mask.match was set to `1` [here](https://github.com/marklawlor/nativewind/blob/6863d0b38414105cc9d6efd2d1100fc1c2a3a23b/packages/nativewind/src/styled/index.tsx#L161)

**To Reproduce**
Use an SVG file (can be wrapped in Js, or imported with a babel plugin)
```svg
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
</svg>
```

and apply a `dark:text-white` class.

**Expected behavior**
It should work for dark mode

**Comment by patlux** [comment] 2023-08-29 05:08
Same here. Any updates on this?

**Comment by Gregoirevda** [comment] 2023-08-29 07:49
Switched to tailwind-rn (I've been using it in another project without issues).

**Comment by robcaldecott** [comment] 2023-11-01 09:07
🤞 this is fixed in the upcoming v4 release

**Closed** 2024-09-02 23:10 UTC
Labels: issue-wipe-pre-v4

**Comment by danstepanov** [comment] 2024-09-02 23:20
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
