### ISSUE TITLE
Nativewind 4.1 and Material Top Tabs - Tab alignment issues

### ISSUE THREAD

**Issue by shovel-kun** [nativewind/nativewind#1039] opened 2024-09-04 22:05 UTC
**Describe the bug**
Original pre 4.1 issue by @bhyoo99: #921

With Nativewind 4.1, the Material Top Tabs component from `react-navigation` fails to align itself properly. The tab bar containers do not take up the remaining space, but the tab bar container indicator does.

Removing the nativewind presets from `babel.config.js` confirms that it is an Nativewind issue.

![Bug](https://github.com/user-attachments/assets/37f3a7fc-abe0-4095-ab8a-27c4f4d397d2)

**Reproduction**
https://github.com/shovel-kun/nativewind-material-top-tabs

**Expected behavior**
It should be aligned like below.
![Hack](https://github.com/user-attachments/assets/a838e01d-7a8d-410b-af6f-e9432414824c)
Note that the workaround below will help the tab bar containers to properly align, however the pressable area does not take up the same space.
```js
screenOptions={{
  // Uncommenting the following lines will fix the tab bar alignment,
  // but the pressable area is still off
  tabBarContentContainerStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
}}>
```

**Comment by shovel-kun** [comment] 2024-09-05 15:11
Related pre-4.1 issue: #937

**Comment by trentcharlie** [comment] 2024-09-05 20:17
@shovel-kun can you check if the component where the styles aren't being applied is a pressable? I've had nativewind pinned to 4.0.13 for a while, attempted to upgrade to 4.0.36 and more recently 4.1.x and none of the styles passed to Pressable worked. So I think these later nativewind versions have some issue when the pressable is passed a style prop. Somehow the prop doesn't get applied. 100% of the issues I've had through the various versions of nativewind has been with Pressable. One version breaks one thing, the next version fixes it but breaks another.

**Comment by ghry5** [comment] 2024-09-19 18:33
Dove a little deeper into this. Turns out it is due to `react-native-tab-view` using a function as style prop for `Pressable` in [PlatformPressable](https://github.com/react-navigation/react-navigation/blob/cfebf105844ac1674eee28ec1ff4ccd30e7895ee/packages/react-native-tab-view/src/PlatformPressable.tsx#L59-L67).

I found a previous issue #847 that seems to indicate nativewind does not seem to support this.
The workarounds listed there would require a change to `react-native-tab-view` on first glance. I guess using a utility like `cn` would work?

**Comment by ghry5** [comment] 2024-09-19 18:52
For my purposes i created a small patch via `pnpm patch react-native-tab-view` which seems to work nicely for now by manually tracking the `pressed` state via the `onPressIn` & `onPressOut`.
```
diff --git a/src/PlatformPressable.tsx b/src/PlatformPressable.tsx
index 1e1b18d6a699e1d2cfae7571e2f5b99fc4143e6e..eb97018a37d51150e9eccef0e18cc0436e24cf60 100644
--- a/src/PlatformPressable.tsx
+++ b/src/PlatformPressable.tsx
@@ -23,8 +23,11 @@ export function PlatformPressable({
   pressColor = 'rgba(0, 0, 0, .32)',
   pressOpacity,
   style,
+  onPressIn,
+  onPressOut,
   ...rest
 }: Props) {
+  const [pressed, setPressed] = React.useState(false);
   return (
     <Pressable
       android_ripple={
@@ -32,10 +35,19 @@ export function PlatformPressable({
           ? { color: pressColor, ...android_ripple }
           : undefined
       }
-      style={({ pressed }) => [
+      style={[
         { opacity: pressed && !ANDROID_SUPPORTS_RIPPLE ? pressOpacity : 1 },
         typeof style === 'function' ? style({ pressed }) : style,
       ]}
+      onPressIn={(event) => {
+        onPressIn && onPressIn(event);
+        setPressed(true);
+      }}
+      onPressOut={(event) => {
+          onPressOut && onPressOut(event);
+          setPressed(false);
+      }}
+
       {...rest}
     />
   );
```

**Comment by danstepanov** [comment] 2024-09-28 20:30
> Dove a little deeper into this. Turns out it is due to `react-native-tab-view` using a function as style prop for `Pressable` in [PlatformPressable](https://github.com/react-navigation/react-navigation/blob/cfebf105844ac1674eee28ec1ff4ccd30e7895ee/packages/react-native-tab-view/src/PlatformPressable.tsx#L59-L67).
> 
> 
> 
> I found a previous issue #847 that seems to indicate nativewind does not seem to support this.
> 
> The workarounds listed there would require a change to `react-native-tab-view` on first glance. I guess using a utility like `cn` would work?

Going to close this as this doesn't seem to be an issue related to nativewind

**Closed** 2024-09-28 20:30 UTC
Labels: bug, v4.1

**Comment by ConnorLanglois** [comment] 2024-09-28 20:32
> > Dove a little deeper into this. Turns out it is due to `react-native-tab-view` using a function as style prop for `Pressable` in [PlatformPressable](https://github.com/react-navigation/react-navigation/blob/cfebf105844ac1674eee28ec1ff4ccd30e7895ee/packages/react-native-tab-view/src/PlatformPressable.tsx#L59-L67).
> > I found a previous issue #847 that seems to indicate nativewind does not seem to support this.
> > The workarounds listed there would require a change to `react-native-tab-view` on first glance. I guess using a utility like `cn` would work?
> 
> Going to close this as this doesn't seem to be an issue related to nativewind

Hi Dan,

I believe this is an issue with nativewind specifically. Please see issue #1105 I created to provide a reproduction for this bug.

Thank you

**Comment by hirbod** [comment] 2024-10-01 09:40
@danstepanov that is indeed caused by NativeWind, we just ran into the same problem

**Comment by eyupdogan** [comment] 2024-11-28 07:19
> **Describe the bug** Original pre 4.1 issue by @bhyoo99: #921
> 
> With Nativewind 4.1, the Material Top Tabs component from `react-navigation` fails to align itself properly. The tab bar containers do not take up the remaining space, but the tab bar container indicator does.
> 
> Removing the nativewind presets from `babel.config.js` confirms that it is an Nativewind issue.
> 
> ![Bug](https://private-user-images.githubusercontent.com/164317648/364560929-37f3a7fc-abe0-4095-ab8a-27c4f4d397d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Nzg0MzksIm5iZiI6MTczMjc3ODEzOSwicGF0aCI6Ii8xNjQzMTc2NDgvMzY0NTYwOTI5LTM3ZjNhN2ZjLWFiZTAtNDA5NS1hYjhhLTI3YzRmNGQzOTdkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwNzE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmQxZTBjZDg2ZjdkN2NlOGEyNjhkZjMxNGU1ODU5MTBjZTFkY2QzZjU2ZjJhNjY5ZTBkMmNmMTM0MjdiMWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-q2NXgkx7kkDkn8A7k93cEctGZOBNRV_MGAidvvdECQ)
> 
> **Reproduction** https://github.com/shovel-kun/nativewind-material-top-tabs
> 
> **Expected behavior** It should be aligned like below. ![Hack](https://private-user-images.githubusercontent.com/164317648/364560963-a838e01d-7a8d-410b-af6f-e9432414824c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Nzg0MzksIm5iZiI6MTczMjc3ODEzOSwicGF0aCI6Ii8xNjQzMTc2NDgvMzY0NTYwOTYzLWE4MzhlMDFkLTdhOGQtNDEwYi1hZjZmLWU5NDMyNDE0ODI0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwNzE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTZlMWQ2NTk3Zjk1NGRjYjc5MTc5ZjEzNmMyNjk4MGMyZjIzM2Y5NzUyNjc4MjdhZmI4MzFhODIxYTMzNTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qWGdM8gi3pXoFO38JLiabG3Z221SSoI4troBOT3J3E4) Note that the workaround below will help the tab bar containers to properly align, however the pressable area does not take up the same space.
> 
> ```js
> screenOptions={{
>   // Uncommenting the following lines will fix the tab bar alignment,
>   // but the pressable area is still off
>   tabBarContentContainerStyle: {
>     flex: 1,
>     flexDirection: 'row',
>     justifyContent: 'space-around',
>   },
> }}>
> ```

You should use with property like below

  const TAB_BAR_MARGIN = 12;
  
  const TABBAR_ITEM_WIDTH = (SCREEN_WIDTH - TAB_BAR_MARGIN * 2) / TAB_COUNT //********
    
    //...
    
      screenOptions={{tabBarItemStyle: {
        height: topBarHeight,
        alignItems: 'center',
        justifyContent: 'center',
        width: TABBAR_ITEM_WIDTH //********
      }}}

**Comment by zguo123** [comment] 2025-01-27 05:07
Are the developers actively working on this issue? I am still experiencing this issue with Nativewind! I used the example provide don't he homepage of this repo: https://github.com/PedroBern/react-native-collapsible-tab-view

<img width="473" alt="Image" src="https://github.com/user-attachments/assets/0427fa69-44b9-4848-8b2b-f119b01a875d" />

**Comment by patel-malav** [comment] 2025-03-05 04:50
> For my purposes i created a small patch via `pnpm patch react-native-tab-view` which seems to work nicely for now by manually tracking the `pressed` state via the `onPressIn` & `onPressOut`.
> 
> ```
> diff --git a/src/PlatformPressable.tsx b/src/PlatformPressable.tsx
> index 1e1b18d6a699e1d2cfae7571e2f5b99fc4143e6e..eb97018a37d51150e9eccef0e18cc0436e24cf60 100644
> --- a/src/PlatformPressable.tsx
> +++ b/src/PlatformPressable.tsx
> @@ -23,8 +23,11 @@ export function PlatformPressable({
>    pressColor = 'rgba(0, 0, 0, .32)',
>    pressOpacity,
>    style,
> +  onPressIn,
> +  onPressOut,
>    ...rest
>  }: Props) {
> +  const [pressed, setPressed] = React.useState(false);
>    return (
>      <Pressable
>        android_ripple={
> @@ -32,10 +35,19 @@ export function PlatformPressable({
>            ? { color: pressColor, ...android_ripple }
>            : undefined
>        }
> -      style={({ pressed }) => [
> +      style={[
>          { opacity: pressed && !ANDROID_SUPPORTS_RIPPLE ? pressOpacity : 1 },
>          typeof style === 'function' ? style({ pressed }) : style,
>        ]}
> +      onPressIn={(event) => {
> +        onPressIn && onPressIn(event);
> +        setPressed(true);
> +      }}
> +      onPressOut={(event) => {
> +          onPressOut && onPressOut(event);
> +          setPressed(false);
> +      }}
> +
>        {...rest}
>      />
>    );
> ```

Following on the same thought process, this is a new patch I have created that just add single line change

```
diff --git a/src/PlatformPressable.tsx b/src/PlatformPressable.tsx
index 1e1b18d6a699e1d2cfae7571e2f5b99fc4143e6e..d40fc884a4431bc25c3dbbe663999bf63aa3bd33 100644
--- a/src/PlatformPressable.tsx
+++ b/src/PlatformPressable.tsx
@@ -27,6 +27,7 @@ export function PlatformPressable({
 }: Props) {
   return (
     <Pressable
+      cssInterop={false}
       android_ripple={
         ANDROID_SUPPORTS_RIPPLE
           ? { color: pressColor, ...android_ripple }
```

the cssInterop disables styling for Pressable for this component only

**Comment by rayanfer** [comment] 2025-07-03 05:35
Try this 

`import { Pressable } from 'react-native-gesture-handler';`
